# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuracoesPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgTabConfiguracoes(object):
    def setupUi(self, wdgTabConfiguracoes):
        wdgTabConfiguracoes.setObjectName("wdgTabConfiguracoes")
        wdgTabConfiguracoes.resize(945, 611)
        wdgTabConfiguracoes.setMinimumSize(QtCore.QSize(945, 611))
        wdgTabConfiguracoes.setStyleSheet("#tabMain, #tabTetosPrev {\n"
"    border-radius: 8px;\n"
"    background-color: white;\n"
"    padding: 4px;\n"
"    \n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"#tabMain::pane {\n"
"    background-color: white;\n"
"    border-radius: 8px;\n"
"/*    border-top: 4px solid rgb(52, 73, 94);\n"
"    border-bottom: 4px solid rgb(52, 73, 94);\n"
"    border-right: 4px solid rgb(52, 73, 94);\n"
"    border-left: 4px solid rgba(66, 147, 215, 255);*/\n"
"\n"
"    border: 4px solid transparent;\n"
"}\n"
"\n"
"#tabMain::tab-bar {\n"
"    left: 16px;\n"
"}\n"
"\n"
"QTabBar::tab{\n"
"    background: rgb(52, 73, 94);\n"
"    color: white;\n"
"    min-width: 24ex;\n"
"    margin-left: 4px;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: white;\n"
"    color: rgb(52, 73, 94);\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    border: 2px solid white;\n"
"    padding: 4px;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(wdgTabConfiguracoes)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabMain = QtWidgets.QTabWidget(wdgTabConfiguracoes)
        self.tabMain.setMinimumSize(QtCore.QSize(0, 0))
        self.tabMain.setObjectName("tabMain")
        self.tabTetosPrev = QtWidgets.QWidget()
        self.tabTetosPrev.setStyleSheet("/*------------------------------------ Tables --------------------------------------*/\n"
"#tblTetos{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"#tblTetos::item{\n"
"    margin: 4px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(52, 73, 94);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    min-height: 45px;\n"
"}\n"
"\n"
"QHeaderView::down-arrow {\n"
"    icon-color: white;\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    icon-color: white;\n"
"}\n"
"\n"
"/*-------------------------------- Labels -----------------------------------------*/\n"
"#lbTitulo {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 24px;\n"
"}\n"
"\n"
"#lbSubtitulo, #lbInfoValor,\n"
"#lbInfoData, #lbInfoAcao {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;    \n"
"}\n"
"\n"
"#lbInfoTitulo {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 14px;\n"
"\n"
"    background-color: white;    \n"
"}\n"
"\n"
"/*-------------------------------- Push Buttons --------------------------------*/\n"
"#pbBuscarArq, #pbEditar, \n"
"#pbExcluir, #pbInserir, \n"
"#pbEfetivar  {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 14px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    background-color: rgb(52, 73, 94);\n"
"}\n"
"\n"
"#pbBuscarArq:hover, #pbEditar:hover, \n"
"#pbExcluir:hover, #pbInserir:hover,\n"
"#pbEfetivar:hover {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 14px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    border: 1px solid;\n"
"    background-color: rgb(72, 93, 114);\n"
"}\n"
"\n"
"#pbCancelar {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 14px;\n"
"    color: black;\n"
"\n"
"    border-radius: 4px;\n"
"    background-color: rgb(225, 224, 53);\n"
"}\n"
"\n"
"#pbCancelar:hover {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 14px;\n"
"    color: black;\n"
"\n"
"    border-radius: 4px;\n"
"    background-color: rgb(225, 240, 73);\n"
"}\n"
"\n"
"/*-------------------------------- Frames -----------------------------------------*/\n"
"#frInfo{\n"
"    border-radius: 4px;\n"
"    border: 1px solid rgb(85, 87, 83);\n"
"\n"
"    background-color: white;\n"
"}\n"
"")
        self.tabTetosPrev.setObjectName("tabTetosPrev")
        self.tblTetos = QtWidgets.QTableWidget(self.tabTetosPrev)
        self.tblTetos.setGeometry(QtCore.QRect(10, 180, 471, 371))
        self.tblTetos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblTetos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblTetos.setTextElideMode(QtCore.Qt.ElideNone)
        self.tblTetos.setObjectName("tblTetos")
        self.tblTetos.setColumnCount(3)
        self.tblTetos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblTetos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("TeX Gyre Adventor")
        font.setPointSize(14)
        item.setFont(font)
        self.tblTetos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("TeX Gyre Adventor")
        font.setPointSize(14)
        item.setFont(font)
        self.tblTetos.setHorizontalHeaderItem(2, item)
        self.tblTetos.horizontalHeader().setCascadingSectionResizes(True)
        self.tblTetos.horizontalHeader().setStretchLastSection(True)
        self.tblTetos.verticalHeader().setVisible(False)
        self.lbTitulo = QtWidgets.QLabel(self.tabTetosPrev)
        self.lbTitulo.setGeometry(QtCore.QRect(30, 10, 451, 31))
        self.lbTitulo.setObjectName("lbTitulo")
        self.lbSubtitulo = QtWidgets.QLabel(self.tabTetosPrev)
        self.lbSubtitulo.setGeometry(QtCore.QRect(30, 40, 371, 21))
        self.lbSubtitulo.setObjectName("lbSubtitulo")
        self.pbBuscarArq = QtWidgets.QPushButton(self.tabTetosPrev)
        self.pbBuscarArq.setGeometry(QtCore.QRect(500, 20, 111, 41))
        self.pbBuscarArq.setObjectName("pbBuscarArq")
        self.pbInserir = QtWidgets.QPushButton(self.tabTetosPrev)
        self.pbInserir.setGeometry(QtCore.QRect(500, 160, 111, 25))
        self.pbInserir.setObjectName("pbInserir")
        self.pbExcluir = QtWidgets.QPushButton(self.tabTetosPrev)
        self.pbExcluir.setGeometry(QtCore.QRect(500, 210, 111, 25))
        self.pbExcluir.setObjectName("pbExcluir")
        self.pbEditar = QtWidgets.QPushButton(self.tabTetosPrev)
        self.pbEditar.setGeometry(QtCore.QRect(500, 260, 111, 25))
        self.pbEditar.setObjectName("pbEditar")
        self.frInfo = QtWidgets.QFrame(self.tabTetosPrev)
        self.frInfo.setGeometry(QtCore.QRect(10, 90, 471, 81))
        self.frInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfo.setObjectName("frInfo")
        self.lbInfoData = QtWidgets.QLabel(self.frInfo)
        self.lbInfoData.setGeometry(QtCore.QRect(20, 20, 64, 17))
        self.lbInfoData.setObjectName("lbInfoData")
        self.lbInfoValor = QtWidgets.QLabel(self.frInfo)
        self.lbInfoValor.setGeometry(QtCore.QRect(160, 20, 64, 17))
        self.lbInfoValor.setObjectName("lbInfoValor")
        self.dtData = QtWidgets.QDateEdit(self.frInfo)
        self.dtData.setGeometry(QtCore.QRect(20, 40, 110, 26))
        self.dtData.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dtData.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.dtData.setCalendarPopup(True)
        self.dtData.setObjectName("dtData")
        self.leValor = QtWidgets.QLineEdit(self.frInfo)
        self.leValor.setGeometry(QtCore.QRect(160, 40, 91, 25))
        self.leValor.setObjectName("leValor")
        self.lbInfoAcao = QtWidgets.QLabel(self.frInfo)
        self.lbInfoAcao.setGeometry(QtCore.QRect(300, 10, 161, 20))
        self.lbInfoAcao.setObjectName("lbInfoAcao")
        self.pbEfetivar = QtWidgets.QPushButton(self.frInfo)
        self.pbEfetivar.setGeometry(QtCore.QRect(280, 40, 83, 25))
        self.pbEfetivar.setObjectName("pbEfetivar")
        self.pbCancelar = QtWidgets.QPushButton(self.frInfo)
        self.pbCancelar.setGeometry(QtCore.QRect(380, 40, 83, 25))
        self.pbCancelar.setObjectName("pbCancelar")
        self.lbInfoTitulo = QtWidgets.QLabel(self.tabTetosPrev)
        self.lbInfoTitulo.setGeometry(QtCore.QRect(30, 80, 111, 17))
        self.lbInfoTitulo.setObjectName("lbInfoTitulo")
        self.frInfo.raise_()
        self.tblTetos.raise_()
        self.lbTitulo.raise_()
        self.lbSubtitulo.raise_()
        self.pbBuscarArq.raise_()
        self.pbInserir.raise_()
        self.pbExcluir.raise_()
        self.pbEditar.raise_()
        self.lbInfoTitulo.raise_()
        self.tabMain.addTab(self.tabTetosPrev, "")
        self.clientes = QtWidgets.QWidget()
        self.clientes.setObjectName("clientes")
        self.tabMain.addTab(self.clientes, "")
        self.horizontalLayout.addWidget(self.tabMain)

        self.retranslateUi(wdgTabConfiguracoes)
        self.tabMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(wdgTabConfiguracoes)

    def retranslateUi(self, wdgTabConfiguracoes):
        _translate = QtCore.QCoreApplication.translate
        wdgTabConfiguracoes.setWindowTitle(_translate("wdgTabConfiguracoes", "Form"))
        item = self.tblTetos.horizontalHeaderItem(0)
        item.setText(_translate("wdgTabConfiguracoes", "tetoId"))
        item = self.tblTetos.horizontalHeaderItem(1)
        item.setText(_translate("wdgTabConfiguracoes", "Data"))
        item = self.tblTetos.horizontalHeaderItem(2)
        item.setText(_translate("wdgTabConfiguracoes", "Valor"))
        self.lbTitulo.setText(_translate("wdgTabConfiguracoes", "Histórico dos tetos previdenciários"))
        self.lbSubtitulo.setText(_translate("wdgTabConfiguracoes", "Procure por tetos previdenciários desde 1960"))
        self.pbBuscarArq.setText(_translate("wdgTabConfiguracoes", "Buscar \n"
"arquivo"))
        self.pbInserir.setText(_translate("wdgTabConfiguracoes", "Inserir"))
        self.pbExcluir.setText(_translate("wdgTabConfiguracoes", "Excluir"))
        self.pbEditar.setText(_translate("wdgTabConfiguracoes", "Editar"))
        self.lbInfoData.setText(_translate("wdgTabConfiguracoes", "Data"))
        self.lbInfoValor.setText(_translate("wdgTabConfiguracoes", "Valor"))
        self.dtData.setDisplayFormat(_translate("wdgTabConfiguracoes", "MM/yyyy"))
        self.lbInfoAcao.setText(_translate("wdgTabConfiguracoes", "Inserir ou cancelar edição"))
        self.pbEfetivar.setText(_translate("wdgTabConfiguracoes", "Efetivar"))
        self.pbCancelar.setText(_translate("wdgTabConfiguracoes", "Cancelar"))
        self.lbInfoTitulo.setText(_translate("wdgTabConfiguracoes", "  Inserir / Editar"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabTetosPrev), _translate("wdgTabConfiguracoes", "Tetos Previdenciários"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.clientes), _translate("wdgTabConfiguracoes", "Clientes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgTabConfiguracoes = QtWidgets.QWidget()
    ui = Ui_wdgTabConfiguracoes()
    ui.setupUi(wdgTabConfiguracoes)
    wdgTabConfiguracoes.show()
    sys.exit(app.exec_())
