# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insereContrib.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mwInsereContrib(object):
    def setupUi(self, mwInsereContrib):
        mwInsereContrib.setObjectName("mwInsereContrib")
        mwInsereContrib.resize(800, 600)
        mwInsereContrib.setStyleSheet("/*-------------------------------- Main Window -------------------------------*/\n"
"#mwInsereContrib {\n"
"    background-color: rgb(52, 73, 94);\n"
"}\n"
"\n"
"/*------------------------------------ Frame ------------------------------------*/\n"
"#frMain {\n"
"    border-radius: 8px;\n"
"    border: 0px solid;    \n"
"    background-color: white;\n"
"}\n"
"\n"
"#frInfo, #frInfoRemCont, \n"
"#frTipoDado, #frInfoBeneficio {\n"
"    border-radius: 8px;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"/*------------------------------------- Label -----------------------------------*/\n"
"\n"
"#lbSubtitulo, #lbInfoNit, \n"
"#lbInfoQtdRem, #lbInfoQtdCont,\n"
"#lbInfoNomeCompleto {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"    \n"
"    background-color: transparent;\n"
"}\n"
"\n"
"#lbNit, #lbQtdRem, \n"
"#lbQtdCont, #lbNomeCompleto {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 14px;\n"
"    background-color: transparent;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#lbTitulo {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 24px;\n"
"}\n"
"\n"
"#lbInfoBeneficio, #lbInfoPessoal,\n"
"#lbInfoRemCont, #lbInfoTipoDado {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 14px;    \n"
"\n"
"    background-color: white;\n"
"}\n"
"\n"
"/*------------------------------ Radio Button -------------------------------------*/\n"
"#rbBeneficio, #rbContribuicao, #rbRemuneracao{\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"\n"
"/*------------------------------ Pushed Button -------------------------------------*/\n"
"#pbConfirmar, #pbCancelar {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 14px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    background-color: rgb(52, 73, 94);\n"
"}\n"
"\n"
"#pbConfirmar:hover, #pbCancelar:hover {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 14px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    border: 1px solid;\n"
"    background-color: rgb(72, 93, 114);\n"
"}")
        self.WdgMain = QtWidgets.QWidget(mwInsereContrib)
        self.WdgMain.setObjectName("WdgMain")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.WdgMain)
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frMain = QtWidgets.QFrame(self.WdgMain)
        self.frMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frMain.setObjectName("frMain")
        self.frInfo = QtWidgets.QFrame(self.frMain)
        self.frInfo.setGeometry(QtCore.QRect(20, 100, 481, 141))
        self.frInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfo.setObjectName("frInfo")
        self.lbInfoNomeCompleto = QtWidgets.QLabel(self.frInfo)
        self.lbInfoNomeCompleto.setGeometry(QtCore.QRect(10, 20, 51, 17))
        self.lbInfoNomeCompleto.setObjectName("lbInfoNomeCompleto")
        self.lbInfoNit = QtWidgets.QLabel(self.frInfo)
        self.lbInfoNit.setGeometry(QtCore.QRect(10, 80, 31, 17))
        self.lbInfoNit.setObjectName("lbInfoNit")
        self.lbInfoQtdRem = QtWidgets.QLabel(self.frInfo)
        self.lbInfoQtdRem.setGeometry(QtCore.QRect(270, 20, 111, 31))
        self.lbInfoQtdRem.setAlignment(QtCore.Qt.AlignCenter)
        self.lbInfoQtdRem.setObjectName("lbInfoQtdRem")
        self.lbInfoQtdCont = QtWidgets.QLabel(self.frInfo)
        self.lbInfoQtdCont.setGeometry(QtCore.QRect(270, 80, 101, 41))
        self.lbInfoQtdCont.setAlignment(QtCore.Qt.AlignCenter)
        self.lbInfoQtdCont.setObjectName("lbInfoQtdCont")
        self.lbNomeCompleto = QtWidgets.QLabel(self.frInfo)
        self.lbNomeCompleto.setGeometry(QtCore.QRect(20, 40, 211, 21))
        self.lbNomeCompleto.setText("")
        self.lbNomeCompleto.setObjectName("lbNomeCompleto")
        self.lbNit = QtWidgets.QLabel(self.frInfo)
        self.lbNit.setGeometry(QtCore.QRect(20, 100, 141, 21))
        self.lbNit.setText("")
        self.lbNit.setObjectName("lbNit")
        self.lbQtdRem = QtWidgets.QLabel(self.frInfo)
        self.lbQtdRem.setGeometry(QtCore.QRect(400, 30, 64, 17))
        self.lbQtdRem.setText("")
        self.lbQtdRem.setObjectName("lbQtdRem")
        self.lbQtdCont = QtWidgets.QLabel(self.frInfo)
        self.lbQtdCont.setGeometry(QtCore.QRect(400, 90, 64, 17))
        self.lbQtdCont.setText("")
        self.lbQtdCont.setObjectName("lbQtdCont")
        self.lbTitulo = QtWidgets.QLabel(self.frMain)
        self.lbTitulo.setGeometry(QtCore.QRect(30, 10, 591, 31))
        self.lbTitulo.setObjectName("lbTitulo")
        self.lbSubtitulo = QtWidgets.QLabel(self.frMain)
        self.lbSubtitulo.setGeometry(QtCore.QRect(30, 50, 511, 17))
        self.lbSubtitulo.setObjectName("lbSubtitulo")
        self.lbInfoPessoal = QtWidgets.QLabel(self.frMain)
        self.lbInfoPessoal.setGeometry(QtCore.QRect(40, 90, 171, 17))
        self.lbInfoPessoal.setObjectName("lbInfoPessoal")
        self.frTipoDado = QtWidgets.QFrame(self.frMain)
        self.frTipoDado.setGeometry(QtCore.QRect(540, 110, 161, 121))
        self.frTipoDado.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frTipoDado.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frTipoDado.setObjectName("frTipoDado")
        self.rbBeneficio = QtWidgets.QRadioButton(self.frTipoDado)
        self.rbBeneficio.setGeometry(QtCore.QRect(20, 30, 106, 23))
        self.rbBeneficio.setObjectName("rbBeneficio")
        self.rbRemuneracao = QtWidgets.QRadioButton(self.frTipoDado)
        self.rbRemuneracao.setGeometry(QtCore.QRect(20, 70, 121, 23))
        self.rbRemuneracao.setObjectName("rbRemuneracao")
        self.rbContribuicao = QtWidgets.QRadioButton(self.frTipoDado)
        self.rbContribuicao.setGeometry(QtCore.QRect(20, 50, 106, 23))
        self.rbContribuicao.setObjectName("rbContribuicao")
        self.lbInfoTipoDado = QtWidgets.QLabel(self.frMain)
        self.lbInfoTipoDado.setGeometry(QtCore.QRect(550, 100, 111, 17))
        self.lbInfoTipoDado.setObjectName("lbInfoTipoDado")
        self.frInfoRemCont = QtWidgets.QFrame(self.frMain)
        self.frInfoRemCont.setGeometry(QtCore.QRect(20, 270, 351, 221))
        self.frInfoRemCont.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frInfoRemCont.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoRemCont.setObjectName("frInfoRemCont")
        self.label = QtWidgets.QLabel(self.frInfoRemCont)
        self.label.setGeometry(QtCore.QRect(210, 40, 101, 17))
        self.label.setObjectName("label")
        self.lbRemCont = QtWidgets.QLabel(self.frInfoRemCont)
        self.lbRemCont.setGeometry(QtCore.QRect(10, 40, 101, 17))
        self.lbRemCont.setObjectName("lbRemCont")
        self.leRemuneracao = QtWidgets.QLineEdit(self.frInfoRemCont)
        self.leRemuneracao.setGeometry(QtCore.QRect(82, 60, 101, 25))
        self.leRemuneracao.setObjectName("leRemuneracao")
        self.lbInfoDataFim = QtWidgets.QLabel(self.frInfoRemCont)
        self.lbInfoDataFim.setGeometry(QtCore.QRect(210, 120, 131, 17))
        self.lbInfoDataFim.setObjectName("lbInfoDataFim")
        self.label_4 = QtWidgets.QLabel(self.frInfoRemCont)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 91, 17))
        self.label_4.setObjectName("label_4")
        self.dtCompetencia = QtWidgets.QDateEdit(self.frInfoRemCont)
        self.dtCompetencia.setGeometry(QtCore.QRect(210, 60, 110, 26))
        self.dtCompetencia.setObjectName("dtCompetencia")
        self.dtFimContRem = QtWidgets.QDateEdit(self.frInfoRemCont)
        self.dtFimContRem.setGeometry(QtCore.QRect(210, 140, 110, 26))
        self.dtFimContRem.setObjectName("dtFimContRem")
        self.cbxIndicadores = QtWidgets.QComboBox(self.frInfoRemCont)
        self.cbxIndicadores.setGeometry(QtCore.QRect(10, 140, 171, 25))
        self.cbxIndicadores.setObjectName("cbxIndicadores")
        self.cbxSinal = QtWidgets.QComboBox(self.frInfoRemCont)
        self.cbxSinal.setGeometry(QtCore.QRect(10, 60, 61, 25))
        self.cbxSinal.setIconSize(QtCore.QSize(16, 16))
        self.cbxSinal.setObjectName("cbxSinal")
        self.lbInfoRemCont = QtWidgets.QLabel(self.frMain)
        self.lbInfoRemCont.setGeometry(QtCore.QRect(40, 260, 221, 17))
        self.lbInfoRemCont.setObjectName("lbInfoRemCont")
        self.lbInfoBeneficio = QtWidgets.QLabel(self.frMain)
        self.lbInfoBeneficio.setGeometry(QtCore.QRect(410, 260, 81, 17))
        self.lbInfoBeneficio.setObjectName("lbInfoBeneficio")
        self.frInfoBeneficio = QtWidgets.QFrame(self.frMain)
        self.frInfoBeneficio.setGeometry(QtCore.QRect(390, 270, 351, 221))
        self.frInfoBeneficio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frInfoBeneficio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoBeneficio.setObjectName("frInfoBeneficio")
        self.label_5 = QtWidgets.QLabel(self.frInfoBeneficio)
        self.label_5.setGeometry(QtCore.QRect(220, 30, 101, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frInfoBeneficio)
        self.label_6.setGeometry(QtCore.QRect(20, 90, 101, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frInfoBeneficio)
        self.label_7.setGeometry(QtCore.QRect(220, 90, 64, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frInfoBeneficio)
        self.label_8.setGeometry(QtCore.QRect(20, 30, 91, 17))
        self.label_8.setObjectName("label_8")
        self.dtInicio = QtWidgets.QDateEdit(self.frInfoBeneficio)
        self.dtInicio.setGeometry(QtCore.QRect(220, 50, 110, 26))
        self.dtInicio.setObjectName("dtInicio")
        self.dtFim = QtWidgets.QDateEdit(self.frInfoBeneficio)
        self.dtFim.setGeometry(QtCore.QRect(220, 110, 110, 26))
        self.dtFim.setObjectName("dtFim")
        self.cbxSituacao = QtWidgets.QComboBox(self.frInfoBeneficio)
        self.cbxSituacao.setGeometry(QtCore.QRect(20, 110, 111, 25))
        self.cbxSituacao.setObjectName("cbxSituacao")
        self.label_9 = QtWidgets.QLabel(self.frInfoBeneficio)
        self.label_9.setGeometry(QtCore.QRect(20, 160, 101, 17))
        self.label_9.setObjectName("label_9")
        self.cbxEspecie = QtWidgets.QComboBox(self.frInfoBeneficio)
        self.cbxEspecie.setGeometry(QtCore.QRect(20, 180, 311, 25))
        self.cbxEspecie.setObjectName("cbxEspecie")
        self.leNb = QtWidgets.QLineEdit(self.frInfoBeneficio)
        self.leNb.setGeometry(QtCore.QRect(20, 50, 113, 25))
        self.leNb.setObjectName("leNb")
        self.pbConfirmar = QtWidgets.QPushButton(self.frMain)
        self.pbConfirmar.setGeometry(QtCore.QRect(650, 520, 83, 25))
        self.pbConfirmar.setObjectName("pbConfirmar")
        self.pbCancelar = QtWidgets.QPushButton(self.frMain)
        self.pbCancelar.setGeometry(QtCore.QRect(550, 520, 83, 25))
        self.pbCancelar.setObjectName("pbCancelar")
        self.lbInfoSistema = QtWidgets.QLabel(self.frMain)
        self.lbInfoSistema.setGeometry(QtCore.QRect(20, 510, 351, 21))
        self.lbInfoSistema.setText("")
        self.lbInfoSistema.setObjectName("lbInfoSistema")
        self.pbarSistema = QtWidgets.QProgressBar(self.frMain)
        self.pbarSistema.setGeometry(QtCore.QRect(20, 540, 351, 16))
        self.pbarSistema.setProperty("value", 24)
        self.pbarSistema.setTextVisible(False)
        self.pbarSistema.setObjectName("pbarSistema")
        self.frInfo.raise_()
        self.lbTitulo.raise_()
        self.lbSubtitulo.raise_()
        self.lbInfoPessoal.raise_()
        self.frTipoDado.raise_()
        self.lbInfoTipoDado.raise_()
        self.frInfoRemCont.raise_()
        self.lbInfoRemCont.raise_()
        self.frInfoBeneficio.raise_()
        self.lbInfoBeneficio.raise_()
        self.pbConfirmar.raise_()
        self.pbCancelar.raise_()
        self.lbInfoSistema.raise_()
        self.pbarSistema.raise_()
        self.verticalLayout.addWidget(self.frMain)
        mwInsereContrib.setCentralWidget(self.WdgMain)

        self.retranslateUi(mwInsereContrib)
        QtCore.QMetaObject.connectSlotsByName(mwInsereContrib)

    def retranslateUi(self, mwInsereContrib):
        _translate = QtCore.QCoreApplication.translate
        mwInsereContrib.setWindowTitle(_translate("mwInsereContrib", "MainWindow"))
        self.lbInfoNomeCompleto.setText(_translate("mwInsereContrib", "Nome:"))
        self.lbInfoNit.setText(_translate("mwInsereContrib", "NIT:"))
        self.lbInfoQtdRem.setText(_translate("mwInsereContrib", "Quantidade de \n"
"Remunerações"))
        self.lbInfoQtdCont.setText(_translate("mwInsereContrib", "Quantidade de \n"
"Contribuições"))
        self.lbTitulo.setText(_translate("mwInsereContrib", "Inserir Contribuição/Remuneração/Benefício"))
        self.lbSubtitulo.setText(_translate("mwInsereContrib", "Insira as informações de uma determinada Contribuição, Remuneração ou Benefício"))
        self.lbInfoPessoal.setText(_translate("mwInsereContrib", "  Informações do cliente"))
        self.rbBeneficio.setText(_translate("mwInsereContrib", "Benefício"))
        self.rbRemuneracao.setText(_translate("mwInsereContrib", "Remuneração"))
        self.rbContribuicao.setText(_translate("mwInsereContrib", "Contribuição"))
        self.lbInfoTipoDado.setText(_translate("mwInsereContrib", "  Tipo de dado"))
        self.label.setText(_translate("mwInsereContrib", "Competência"))
        self.lbRemCont.setText(_translate("mwInsereContrib", "Remuneração"))
        self.lbInfoDataFim.setText(_translate("mwInsereContrib", "Data Fim"))
        self.label_4.setText(_translate("mwInsereContrib", "Indicadores"))
        self.lbInfoRemCont.setText(_translate("mwInsereContrib", "  Remuneração / Contribuição"))
        self.lbInfoBeneficio.setText(_translate("mwInsereContrib", "  Benefício"))
        self.label_5.setText(_translate("mwInsereContrib", "Data Início"))
        self.label_6.setText(_translate("mwInsereContrib", "Situação"))
        self.label_7.setText(_translate("mwInsereContrib", "Data Fim"))
        self.label_8.setText(_translate("mwInsereContrib", "NB"))
        self.label_9.setText(_translate("mwInsereContrib", "Espécie"))
        self.pbConfirmar.setText(_translate("mwInsereContrib", "Confirmar"))
        self.pbCancelar.setText(_translate("mwInsereContrib", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mwInsereContrib = QtWidgets.QMainWindow()
    ui = Ui_mwInsereContrib()
    ui.setupUi(mwInsereContrib)
    mwInsereContrib.show()
    sys.exit(app.exec_())
