# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mwLogin(object):
    def setupUi(self, mwLogin):
        mwLogin.setObjectName("mwLogin")
        mwLogin.resize(950, 500)
        mwLogin.setMinimumSize(QtCore.QSize(950, 500))
        mwLogin.setMaximumSize(QtCore.QSize(950, 500))
        mwLogin.setStyleSheet("#mwLogin, #centralwidget, #stkPrimeiroAcesso {\n"
"    border-radius: 8px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(mwLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frMain = QtWidgets.QFrame(self.centralwidget)
        self.frMain.setStyleSheet("/*---------------------------------- Frame --------------------------------------*/\n"
"#frMain{\n"
"    border-radius: 8px;\n"
"    background-color: rgb(244, 244, 244);\n"
"}\n"
"\n"
"#frRight{\n"
"    border-image: url(:/Logo/LogoLogin.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"#frLogo{\n"
"    border-image: url(:/Logo/LogoLogin.png);\n"
"}\n"
"\n"
"/*---------------------------------- Label --------------------------------------*/\n"
"#lbLogin {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 36px;\n"
"}\n"
"\n"
"#lbNomeDoEscritorio, #lbInfoAcesso{\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"#lbEscritorio {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#lbNLS {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 8px;\n"
"}\n"
"\n"
"/*------------------------------- Push Button ---------------------------------*/\n"
"\n"
"#pbEntrar {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.51, y1:0, x2:0.474, y2:1, stop:0 rgba(58, 171, 140, 255), stop:1 rgba(9, 212, 156, 255));\n"
"}\n"
"\n"
"#pbEntrar:hover {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.51, y1:0, x2:0.474, y2:1, stop:0 rgba(68, 181, 150, 255), stop:1 rgba(19, 222, 166, 255));\n"
"}\n"
"\n"
"#pbPrimeiroAcesso {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.51, y1:0, x2:0.474, y2:1, stop:0 rgba(61, 83, 180, 255), stop:1 rgba(9, 162, 212, 255));\n"
"}\n"
"\n"
"#pbPrimeiroAcesso:hover {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.51, y1:0, x2:0.474, y2:1, stop:0 rgba(81, 103, 200, 255), stop:1 rgba(29, 182, 232, 255));\n"
"}")
        self.frMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frMain.setObjectName("frMain")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frMain)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frLeft = QtWidgets.QFrame(self.frMain)
        self.frLeft.setMinimumSize(QtCore.QSize(400, 0))
        self.frLeft.setMaximumSize(QtCore.QSize(488, 16777215))
        self.frLeft.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frLeft.setObjectName("frLeft")
        self.lbLogin = QtWidgets.QLabel(self.frLeft)
        self.lbLogin.setGeometry(QtCore.QRect(140, 90, 101, 51))
        self.lbLogin.setObjectName("lbLogin")
        self.leLogin = QtWidgets.QLineEdit(self.frLeft)
        self.leLogin.setGeometry(QtCore.QRect(100, 170, 181, 25))
        self.leLogin.setObjectName("leLogin")
        self.leSenha = QtWidgets.QLineEdit(self.frLeft)
        self.leSenha.setGeometry(QtCore.QRect(100, 210, 181, 25))
        self.leSenha.setObjectName("leSenha")
        self.lbEscritorio = QtWidgets.QLabel(self.frLeft)
        self.lbEscritorio.setGeometry(QtCore.QRect(10, 10, 71, 31))
        self.lbEscritorio.setObjectName("lbEscritorio")
        self.lbNomeDoEscritorio = QtWidgets.QLabel(self.frLeft)
        self.lbNomeDoEscritorio.setGeometry(QtCore.QRect(90, 10, 301, 31))
        self.lbNomeDoEscritorio.setText("")
        self.lbNomeDoEscritorio.setObjectName("lbNomeDoEscritorio")
        self.pbEntrar = QtWidgets.QPushButton(self.frLeft)
        self.pbEntrar.setGeometry(QtCore.QRect(102, 300, 181, 25))
        self.pbEntrar.setObjectName("pbEntrar")
        self.lbNLS = QtWidgets.QLabel(self.frLeft)
        self.lbNLS.setGeometry(QtCore.QRect(100, 240, 171, 17))
        self.lbNLS.setObjectName("lbNLS")
        self.lbInfoAcesso = QtWidgets.QLabel(self.frLeft)
        self.lbInfoAcesso.setGeometry(QtCore.QRect(100, 132, 181, 17))
        self.lbInfoAcesso.setObjectName("lbInfoAcesso")
        self.pbPrimeiroAcesso = QtWidgets.QPushButton(self.frLeft)
        self.pbPrimeiroAcesso.setGeometry(QtCore.QRect(100, 340, 181, 25))
        self.pbPrimeiroAcesso.setObjectName("pbPrimeiroAcesso")
        self.horizontalLayout.addWidget(self.frLeft)
        self.stkPrimeiroAcesso = QtWidgets.QStackedWidget(self.frMain)
        self.stkPrimeiroAcesso.setStyleSheet("/*---------------------------------- Widgets ----------------------------------*/\n"
"\n"
"#wdgVinculado{\n"
"    border-top.left-radius: 0px;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 8px;\n"
"    background-color: rgb(33, 76, 121);\n"
"}\n"
"\n"
"#wdgDesvinculado {\n"
"    border-top.left-radius: 0px;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 8px;\n"
"    border-image: url(:/Logo/LogoLogin.png);\n"
"}\n"
"\n"
"/*---------------------------------- Labels ----------------------------------*/\n"
"\n"
"#lbCdEscritorio {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 16px;\n"
"\n"
"    color: rgb(238, 238, 236);\n"
"}\n"
"\n"
"/*---------------------------------- ScrollArea ----------------------------------*/\n"
"\n"
"#scaAdvWidgets, #scaAdvogados{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/*---------------------------------- Push Buttons ----------------------------------*/\n"
"\n"
"#pbBuscar {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.51, y1:0, x2:0.474, y2:1, stop:0 rgba(58, 171, 140, 255), stop:1 rgba(9, 212, 156, 255));\n"
"}\n"
"\n"
"#pbBuscar:hover {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.51, y1:0, x2:0.474, y2:1, stop:0 rgba(9, 212, 156, 255), stop:1 rgba(58, 171, 140, 255));\n"
"}\n"
"")
        self.stkPrimeiroAcesso.setObjectName("stkPrimeiroAcesso")
        self.wdgVinculado = QtWidgets.QWidget()
        self.wdgVinculado.setObjectName("wdgVinculado")
        self.lbCdEscritorio = QtWidgets.QLabel(self.wdgVinculado)
        self.lbCdEscritorio.setGeometry(QtCore.QRect(30, 20, 171, 21))
        self.lbCdEscritorio.setObjectName("lbCdEscritorio")
        self.leCdEscritorio = QtWidgets.QLineEdit(self.wdgVinculado)
        self.leCdEscritorio.setGeometry(QtCore.QRect(220, 20, 211, 25))
        self.leCdEscritorio.setObjectName("leCdEscritorio")
        self.scaAdvogados = QtWidgets.QScrollArea(self.wdgVinculado)
        self.scaAdvogados.setGeometry(QtCore.QRect(10, 60, 530, 430))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaAdvogados.sizePolicy().hasHeightForWidth())
        self.scaAdvogados.setSizePolicy(sizePolicy)
        self.scaAdvogados.setMinimumSize(QtCore.QSize(530, 430))
        self.scaAdvogados.setMaximumSize(QtCore.QSize(530, 430))
        self.scaAdvogados.setWidgetResizable(True)
        self.scaAdvogados.setObjectName("scaAdvogados")
        self.scaAdvWidgets = QtWidgets.QWidget()
        self.scaAdvWidgets.setGeometry(QtCore.QRect(0, 0, 528, 428))
        self.scaAdvWidgets.setObjectName("scaAdvWidgets")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scaAdvWidgets)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.vlAdv = QtWidgets.QVBoxLayout()
        self.vlAdv.setObjectName("vlAdv")
        self.verticalLayout_3.addLayout(self.vlAdv)
        self.scaAdvogados.setWidget(self.scaAdvWidgets)
        self.pbBuscar = QtWidgets.QPushButton(self.wdgVinculado)
        self.pbBuscar.setGeometry(QtCore.QRect(450, 20, 83, 25))
        self.pbBuscar.setObjectName("pbBuscar")
        self.stkPrimeiroAcesso.addWidget(self.wdgVinculado)
        self.wdgDesvinculado = QtWidgets.QWidget()
        self.wdgDesvinculado.setObjectName("wdgDesvinculado")
        self.stkPrimeiroAcesso.addWidget(self.wdgDesvinculado)
        self.horizontalLayout.addWidget(self.stkPrimeiroAcesso)
        self.horizontalLayout_2.addWidget(self.frMain)
        mwLogin.setCentralWidget(self.centralwidget)

        self.retranslateUi(mwLogin)
        QtCore.QMetaObject.connectSlotsByName(mwLogin)

    def retranslateUi(self, mwLogin):
        _translate = QtCore.QCoreApplication.translate
        mwLogin.setWindowTitle(_translate("mwLogin", "MainWindow"))
        self.lbLogin.setText(_translate("mwLogin", "Login"))
        self.leLogin.setPlaceholderText(_translate("mwLogin", "Nº OAB ou E-mail"))
        self.leSenha.setPlaceholderText(_translate("mwLogin", "Senha"))
        self.lbEscritorio.setText(_translate("mwLogin", "Escritório:"))
        self.pbEntrar.setText(_translate("mwLogin", "Entrar"))
        self.lbNLS.setText(_translate("mwLogin", "Não lembro minha senha"))
        self.lbInfoAcesso.setText(_translate("mwLogin", "Acesse a sua conta"))
        self.pbPrimeiroAcesso.setText(_translate("mwLogin", "Primeiro acesso"))
        self.lbCdEscritorio.setText(_translate("mwLogin", "Código do escritório:"))
        self.pbBuscar.setText(_translate("mwLogin", "Buscar"))
import Resources.loginResources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mwLogin = QtWidgets.QMainWindow()
    ui = Ui_mwLogin()
    ui.setupUi(mwLogin)
    mwLogin.show()
    sys.exit(app.exec_())
