# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pgImpressaoDocs.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgImpressaoDocs(object):
    def setupUi(self, wdgImpressaoDocs):
        wdgImpressaoDocs.setObjectName("wdgImpressaoDocs")
        wdgImpressaoDocs.resize(891, 665)
        wdgImpressaoDocs.setStyleSheet("/* ------------------------------ Widgets ------------------------------ */\n"
"#wdgNatureza{\n"
"    background-color: transparent;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/* ------------------------------ Frames ------------------------------ */\n"
"#frMain{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 246, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"#frProcuracao, #frDocsComprob {\n"
"    background-color: rgb(32, 74, 135);\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"#frOutro1, #frOutro2 {\n"
"    background-color: rgb(52, 94, 155);\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"#frOutro3, #frOutro4 {\n"
"    background-color: rgb(72, 94, 175);\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"#frOutro5, #frOutro6 {\n"
"    background-color: rgb(92, 114, 195);\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"#frAtiv1, #frAtiv4, #frAtiv7, \n"
"#frAtiv8, #frAtiv9, #frAtiv10  {\n"
"    background-image: url(:/info/information.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}\n"
"\n"
"/* ------------------------------ Labels ------------------------------ */\n"
"#lbTituloNatureza, #lbOu {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 24px;\n"
"\n"
"    color: grey;\n"
"}\n"
"\n"
"/* ------------------------------ CheckBox ------------------------------ */\n"
"#cbProcuracao, #cbDocsComprob, #cbAtiv3, \n"
"#cbAtiv4, #cbAtiv5, #cbAtiv6, \n"
"#cbAtiv7, #cbAtiv8, #cbAtiv9, \n"
"#cbAtiv10, #cbAtiv11, #cbAtiv12, \n"
"#cbAtiv13, #cbAtiv14, #cbAtiv15, \n"
"#cbAtiv16 {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 24px;\n"
"\n"
"    color: white;\n"
"}\n"
"\n"
"#cbProcuracao::indicator , #cbDocsComprob::indicator , #cbAtiv3::indicator , \n"
"#cbAtiv4::indicator , #cbAtiv5::indicator , #cbAtiv6::indicator , \n"
"#cbAtiv7::indicator , #cbAtiv8::indicator , #cbAtiv9::indicator , \n"
"#cbAtiv10::indicator , #cbAtiv11::indicator , #cbAtiv12::indicator , \n"
"#cbAtiv13::indicator, #cbAtiv14::indicator, #cbAtiv15::indicator, \n"
"#cbAtiv16::indicator {\n"
"    width: 24px;\n"
"    height: 24px;\n"
"}\n"
"\n"
"/* ------------------------------ Push Buttons ------------------------------ */\n"
"#pbApos, #pbAposDeficiencia, #pbAposEspecial,\n"
"#pbAposRural, #pbAuxReclusao, #pbAuxilioDoenca,\n"
"#pbBeneDeficiencia, #pbBeneIdoso, #pbPensaoMorte,\n"
"#pbSalMaternidade {\n"
"    background-color: rgb(117, 80, 123);\n"
"    border-radius: 16px;\n"
"\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 24px;\n"
"    color: white;    \n"
"}\n"
"\n"
"#pbApos:hover, #pbApos:hover, #pbAposDeficiencia:hover, #pbAposEspecial:hover,\n"
"#pbAposRural:hover, #pbAuxReclusao:hover, #pbAuxilioDoenca:hover,\n"
"#pbBeneDeficiencia:hover, #pbBeneIdoso:hover, #pbPensaoMorte:hover,\n"
"#pbSalMaternidade:hover {\n"
"    background-color: rgb(115, 210, 22);\n"
"    border-radius: 16px;\n"
"\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 24px;\n"
"    color: white;    \n"
"}\n"
"\n"
"/* ------------------------------ Scroll Area ------------------------------ */\n"
"#scrollArea, #scrollCentral {\n"
"    background-color: transparent;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(wdgImpressaoDocs)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frMain = QtWidgets.QFrame(wdgImpressaoDocs)
        self.frMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frMain.setObjectName("frMain")
        self.gridLayout = QtWidgets.QGridLayout(self.frMain)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.frMain)
        self.frame_2.setMaximumSize(QtCore.QSize(16777214, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbTituloNatureza = QtWidgets.QLabel(self.frame_2)
        self.lbTituloNatureza.setObjectName("lbTituloNatureza")
        self.horizontalLayout.addWidget(self.lbTituloNatureza)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.frMain)
        self.scrollArea.setMinimumSize(QtCore.QSize(830, 600))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollCentral = QtWidgets.QWidget()
        self.scrollCentral.setGeometry(QtCore.QRect(0, 0, 875, 700))
        self.scrollCentral.setObjectName("scrollCentral")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollCentral)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frProcuracao = QtWidgets.QFrame(self.scrollCentral)
        self.frProcuracao.setMinimumSize(QtCore.QSize(800, 80))
        self.frProcuracao.setMaximumSize(QtCore.QSize(800, 80))
        self.frProcuracao.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frProcuracao.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frProcuracao.setObjectName("frProcuracao")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frProcuracao)
        self.horizontalLayout_14.setContentsMargins(16, 4, 32, 4)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.cbProcuracao = QtWidgets.QCheckBox(self.frProcuracao)
        self.cbProcuracao.setObjectName("cbProcuracao")
        self.horizontalLayout_14.addWidget(self.cbProcuracao)
        self.frAtiv1 = QtWidgets.QFrame(self.frProcuracao)
        self.frAtiv1.setMinimumSize(QtCore.QSize(36, 36))
        self.frAtiv1.setMaximumSize(QtCore.QSize(36, 36))
        self.frAtiv1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frAtiv1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frAtiv1.setObjectName("frAtiv1")
        self.horizontalLayout_14.addWidget(self.frAtiv1)
        self.verticalLayout_2.addWidget(self.frProcuracao, 0, QtCore.Qt.AlignHCenter)
        self.frDocsComprob = QtWidgets.QFrame(self.scrollCentral)
        self.frDocsComprob.setMinimumSize(QtCore.QSize(800, 80))
        self.frDocsComprob.setMaximumSize(QtCore.QSize(800, 80))
        self.frDocsComprob.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frDocsComprob.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frDocsComprob.setObjectName("frDocsComprob")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frDocsComprob)
        self.horizontalLayout_3.setContentsMargins(16, 4, 4, 4)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cbDocsComprob = QtWidgets.QCheckBox(self.frDocsComprob)
        self.cbDocsComprob.setObjectName("cbDocsComprob")
        self.horizontalLayout_3.addWidget(self.cbDocsComprob)
        self.verticalLayout_2.addWidget(self.frDocsComprob, 0, QtCore.Qt.AlignHCenter)
        self.frOutro1 = QtWidgets.QFrame(self.scrollCentral)
        self.frOutro1.setMinimumSize(QtCore.QSize(800, 80))
        self.frOutro1.setMaximumSize(QtCore.QSize(800, 80))
        self.frOutro1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frOutro1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frOutro1.setObjectName("frOutro1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frOutro1)
        self.horizontalLayout_4.setContentsMargins(16, 4, 4, 4)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cbAtiv3 = QtWidgets.QCheckBox(self.frOutro1)
        self.cbAtiv3.setObjectName("cbAtiv3")
        self.horizontalLayout_4.addWidget(self.cbAtiv3)
        self.verticalLayout_2.addWidget(self.frOutro1, 0, QtCore.Qt.AlignHCenter)
        self.frOutro2 = QtWidgets.QFrame(self.scrollCentral)
        self.frOutro2.setMinimumSize(QtCore.QSize(800, 80))
        self.frOutro2.setMaximumSize(QtCore.QSize(800, 80))
        self.frOutro2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frOutro2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frOutro2.setObjectName("frOutro2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frOutro2)
        self.horizontalLayout_5.setContentsMargins(16, 4, 32, 4)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cbAtiv4 = QtWidgets.QCheckBox(self.frOutro2)
        self.cbAtiv4.setObjectName("cbAtiv4")
        self.horizontalLayout_5.addWidget(self.cbAtiv4)
        self.frAtiv4 = QtWidgets.QFrame(self.frOutro2)
        self.frAtiv4.setMinimumSize(QtCore.QSize(36, 36))
        self.frAtiv4.setMaximumSize(QtCore.QSize(36, 36))
        self.frAtiv4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frAtiv4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frAtiv4.setObjectName("frAtiv4")
        self.horizontalLayout_5.addWidget(self.frAtiv4)
        self.verticalLayout_2.addWidget(self.frOutro2, 0, QtCore.Qt.AlignHCenter)
        self.frOutro3 = QtWidgets.QFrame(self.scrollCentral)
        self.frOutro3.setMinimumSize(QtCore.QSize(800, 80))
        self.frOutro3.setMaximumSize(QtCore.QSize(800, 80))
        self.frOutro3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frOutro3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frOutro3.setObjectName("frOutro3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frOutro3)
        self.horizontalLayout_6.setContentsMargins(16, 4, 4, 4)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cbAtiv5 = QtWidgets.QCheckBox(self.frOutro3)
        self.cbAtiv5.setObjectName("cbAtiv5")
        self.horizontalLayout_6.addWidget(self.cbAtiv5)
        self.verticalLayout_2.addWidget(self.frOutro3, 0, QtCore.Qt.AlignHCenter)
        self.frOutro4 = QtWidgets.QFrame(self.scrollCentral)
        self.frOutro4.setMinimumSize(QtCore.QSize(800, 80))
        self.frOutro4.setMaximumSize(QtCore.QSize(800, 80))
        self.frOutro4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frOutro4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frOutro4.setObjectName("frOutro4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frOutro4)
        self.horizontalLayout_7.setContentsMargins(16, 4, 4, 4)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cbAtiv6 = QtWidgets.QCheckBox(self.frOutro4)
        self.cbAtiv6.setObjectName("cbAtiv6")
        self.horizontalLayout_7.addWidget(self.cbAtiv6)
        self.verticalLayout_2.addWidget(self.frOutro4, 0, QtCore.Qt.AlignHCenter)
        self.frOutro5 = QtWidgets.QFrame(self.scrollCentral)
        self.frOutro5.setMinimumSize(QtCore.QSize(800, 80))
        self.frOutro5.setMaximumSize(QtCore.QSize(800, 80))
        self.frOutro5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frOutro5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frOutro5.setObjectName("frOutro5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frOutro5)
        self.horizontalLayout_8.setContentsMargins(16, 4, 32, 4)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.cbAtiv7 = QtWidgets.QCheckBox(self.frOutro5)
        self.cbAtiv7.setObjectName("cbAtiv7")
        self.horizontalLayout_8.addWidget(self.cbAtiv7)
        self.frAtiv7 = QtWidgets.QFrame(self.frOutro5)
        self.frAtiv7.setMinimumSize(QtCore.QSize(36, 36))
        self.frAtiv7.setMaximumSize(QtCore.QSize(36, 36))
        self.frAtiv7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frAtiv7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frAtiv7.setObjectName("frAtiv7")
        self.horizontalLayout_8.addWidget(self.frAtiv7)
        self.verticalLayout_2.addWidget(self.frOutro5, 0, QtCore.Qt.AlignHCenter)
        self.frOutro6 = QtWidgets.QFrame(self.scrollCentral)
        self.frOutro6.setMinimumSize(QtCore.QSize(800, 80))
        self.frOutro6.setMaximumSize(QtCore.QSize(800, 80))
        self.frOutro6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frOutro6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frOutro6.setObjectName("frOutro6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frOutro6)
        self.horizontalLayout_9.setContentsMargins(16, 4, 32, 4)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cbAtiv8 = QtWidgets.QCheckBox(self.frOutro6)
        self.cbAtiv8.setObjectName("cbAtiv8")
        self.horizontalLayout_9.addWidget(self.cbAtiv8)
        self.frAtiv8 = QtWidgets.QFrame(self.frOutro6)
        self.frAtiv8.setMinimumSize(QtCore.QSize(36, 36))
        self.frAtiv8.setMaximumSize(QtCore.QSize(36, 36))
        self.frAtiv8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frAtiv8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frAtiv8.setObjectName("frAtiv8")
        self.horizontalLayout_9.addWidget(self.frAtiv8)
        self.verticalLayout_2.addWidget(self.frOutro6, 0, QtCore.Qt.AlignHCenter)
        self.scrollArea.setWidget(self.scrollCentral)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frMain)

        self.retranslateUi(wdgImpressaoDocs)
        QtCore.QMetaObject.connectSlotsByName(wdgImpressaoDocs)

    def retranslateUi(self, wdgImpressaoDocs):
        _translate = QtCore.QCoreApplication.translate
        wdgImpressaoDocs.setWindowTitle(_translate("wdgImpressaoDocs", "Form"))
        self.lbTituloNatureza.setText(_translate("wdgImpressaoDocs", "Selecione quais documentos gostaria de gerar"))
        self.cbProcuracao.setText(_translate("wdgImpressaoDocs", "    Procuração"))
        self.cbDocsComprob.setText(_translate("wdgImpressaoDocs", "    Documentos comprobatórios"))
        self.cbAtiv3.setText(_translate("wdgImpressaoDocs", "    Outro"))
        self.cbAtiv4.setText(_translate("wdgImpressaoDocs", "    Outro"))
        self.cbAtiv5.setText(_translate("wdgImpressaoDocs", "    Outro"))
        self.cbAtiv6.setText(_translate("wdgImpressaoDocs", "    Outro"))
        self.cbAtiv7.setText(_translate("wdgImpressaoDocs", "    Outro"))
        self.cbAtiv8.setText(_translate("wdgImpressaoDocs", "    Outro"))
import Resources.quizApos


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgImpressaoDocs = QtWidgets.QWidget()
    ui = Ui_wdgImpressaoDocs()
    ui.setupUi(wdgImpressaoDocs)
    wdgImpressaoDocs.show()
    sys.exit(app.exec_())
