# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design/UI/buscaProcessos.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mwBuscaProcessos(object):
    def setupUi(self, mwBuscaProcessos):
        mwBuscaProcessos.setObjectName("mwBuscaProcessos")
        mwBuscaProcessos.resize(1039, 608)
        mwBuscaProcessos.setMinimumSize(QtCore.QSize(1039, 608))
        mwBuscaProcessos.setStyleSheet("#centralwidget {\n"
"    background-color: lightgrey;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(mwBuscaProcessos)
        self.centralwidget.setStyleSheet("/* ------------ Geral --------------- */\n"
"QLabel {\n"
"    font: 11pt \"Avenir LT Std\";\n"
"    color: #1F1E29;\n"
"    font-weight: 200;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    border: 0px solid gray;\n"
"    border-radius: 8px;\n"
"       padding: 0 8px;\n"
"    background: #F9F9F9;\n"
"    selection-background-color: darkgray;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 0px solid gray;\n"
"    border-radius: 8px;\n"
"    padding: 1px 18px 1px 8px;\n"
"    \n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: #606970;    \n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #F9F9F9;\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: #F9F9F9;\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    padding: 0px 8px 0px 0px;\n"
"\n"
"    border-left-width: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/arrowDown/down.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"/*-------------------------------------------  Scroll Bar --------------------------------------------*/\n"
"QScrollBar:vertical {\n"
"        background-color: #DDDEDF;\n"
"        width: 15px;\n"
"        margin: 15px 3px 15px 3px;\n"
"        border: 1px transparent #2A2929;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #3F4E8C;\n"
"    min-height: 5px;\n"
"    width: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical{\n"
"      border: none;\n"
"      background: none;\n"
"      color: none;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"/*------------------------------------------- Table Widget -------------------------------------------*/\n"
"#tblListaProcessos {\n"
"    selection-background-color: #F9F9F9;\n"
"    selection-color: grey;\n"
"    gridline-color: white;\n"
"\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"QHeaderView {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: white;\n"
"    padding-left: 4px;\n"
"    border: 0px solid white;\n"
"    min-height: 45px;\n"
"}\n"
"\n"
"#tblListaProcessos::item:last {\n"
"    selection-background-color: black;\n"
"    selection-color: grey;\n"
"    gridline-color: black;\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"#tblListaProcessos::item {\n"
"    padding: 2px 24px 2px 24px;\n"
"}\n"
"\n"
"/* ------------------  Frames --------------------- */\n"
"#frMain {\n"
"    background-color: white;\n"
"    border: 0px solid transparent;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"#frFirulaCliente {\n"
"    background-color: #009E38;\n"
"    border: 0px solid transparent;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"#frInfoCliente {\n"
"    background-color: white;\n"
"    border: 0px solid transparent;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/* ------------------- Label ------------------- */\n"
"#lbTitulo {\n"
"    font: 16pt \"Avenir LT Std\";\n"
"    color: #3F4E8C;\n"
"    font-weight: 750;\n"
"}\n"
"\n"
"#pbSeleciona, #pbCancela {\n"
"    background-color: white;\n"
"    border: 2px solid #3F4E8C;\n"
"    border-radius: 8px;\n"
"\n"
"    \n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: #3F4E8C;\n"
"    font-weight: 750;\n"
"\n"
"    padding: 8px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frMain = QtWidgets.QFrame(self.centralwidget)
        self.frMain.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frMain.setObjectName("frMain")
        self.gridLayout = QtWidgets.QGridLayout(self.frMain)
        self.gridLayout.setObjectName("gridLayout")
        self.frTabela = QtWidgets.QFrame(self.frMain)
        self.frTabela.setStyleSheet("")
        self.frTabela.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frTabela.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frTabela.setObjectName("frTabela")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frTabela)
        self.horizontalLayout_2.setContentsMargins(0, 0, 8, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tblListaProcessos = QtWidgets.QTableWidget(self.frTabela)
        self.tblListaProcessos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblListaProcessos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblListaProcessos.setObjectName("tblListaProcessos")
        self.tblListaProcessos.setColumnCount(5)
        self.tblListaProcessos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Avenir LT Std")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(63, 78, 140))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tblListaProcessos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Avenir LT Std")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(63, 78, 140))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tblListaProcessos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Avenir LT Std")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(63, 78, 140))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tblListaProcessos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Avenir LT Std")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(63, 78, 140))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tblListaProcessos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(63, 78, 140))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tblListaProcessos.setHorizontalHeaderItem(4, item)
        self.tblListaProcessos.horizontalHeader().setCascadingSectionResizes(True)
        self.tblListaProcessos.horizontalHeader().setStretchLastSection(True)
        self.tblListaProcessos.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.tblListaProcessos)
        self.gridLayout.addWidget(self.frTabela, 1, 0, 1, 1)
        self.frCabecalho = QtWidgets.QFrame(self.frMain)
        self.frCabecalho.setStyleSheet("")
        self.frCabecalho.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frCabecalho.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frCabecalho.setObjectName("frCabecalho")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frCabecalho)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbTitulo = QtWidgets.QLabel(self.frCabecalho)
        self.lbTitulo.setObjectName("lbTitulo")
        self.verticalLayout_2.addWidget(self.lbTitulo)
        self.lbSubtitulo = QtWidgets.QLabel(self.frCabecalho)
        self.lbSubtitulo.setIndent(8)
        self.lbSubtitulo.setObjectName("lbSubtitulo")
        self.verticalLayout_2.addWidget(self.lbSubtitulo)
        self.frOrganizadorCards = QtWidgets.QFrame(self.frCabecalho)
        self.frOrganizadorCards.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frOrganizadorCards.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frOrganizadorCards.setObjectName("frOrganizadorCards")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frOrganizadorCards)
        self.horizontalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_3.setSpacing(9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frInfoCliente = QtWidgets.QFrame(self.frOrganizadorCards)
        self.frInfoCliente.setMinimumSize(QtCore.QSize(0, 50))
        self.frInfoCliente.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frInfoCliente.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoCliente.setObjectName("frInfoCliente")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frInfoCliente)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lbInfoTelefone = QtWidgets.QLabel(self.frInfoCliente)
        self.lbInfoTelefone.setObjectName("lbInfoTelefone")
        self.gridLayout_7.addWidget(self.lbInfoTelefone, 1, 1, 1, 1)
        self.lbInfoEmail = QtWidgets.QLabel(self.frInfoCliente)
        self.lbInfoEmail.setObjectName("lbInfoEmail")
        self.gridLayout_7.addWidget(self.lbInfoEmail, 2, 1, 1, 1)
        self.frFirulaCliente = QtWidgets.QFrame(self.frInfoCliente)
        self.frFirulaCliente.setMinimumSize(QtCore.QSize(4, 0))
        self.frFirulaCliente.setMaximumSize(QtCore.QSize(4, 16777215))
        self.frFirulaCliente.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frFirulaCliente.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frFirulaCliente.setObjectName("frFirulaCliente")
        self.gridLayout_7.addWidget(self.frFirulaCliente, 0, 0, 3, 1)
        self.lbEmail = QtWidgets.QLabel(self.frInfoCliente)
        self.lbEmail.setObjectName("lbEmail")
        self.gridLayout_7.addWidget(self.lbEmail, 2, 2, 1, 1)
        self.lbTelefone = QtWidgets.QLabel(self.frInfoCliente)
        self.lbTelefone.setObjectName("lbTelefone")
        self.gridLayout_7.addWidget(self.lbTelefone, 1, 2, 1, 1)
        self.lbNomeCompleto = QtWidgets.QLabel(self.frInfoCliente)
        self.lbNomeCompleto.setObjectName("lbNomeCompleto")
        self.gridLayout_7.addWidget(self.lbNomeCompleto, 0, 1, 1, 2)
        self.horizontalLayout_3.addWidget(self.frInfoCliente, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_2.addWidget(self.frOrganizadorCards)
        self.gridLayout.addWidget(self.frCabecalho, 0, 0, 1, 2)
        self.frSideButtons = QtWidgets.QFrame(self.frMain)
        self.frSideButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frSideButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frSideButtons.setObjectName("frSideButtons")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frSideButtons)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pbSeleciona = QtWidgets.QPushButton(self.frSideButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbSeleciona.sizePolicy().hasHeightForWidth())
        self.pbSeleciona.setSizePolicy(sizePolicy)
        self.pbSeleciona.setMinimumSize(QtCore.QSize(0, 0))
        self.pbSeleciona.setMaximumSize(QtCore.QSize(654654, 1984654))
        self.pbSeleciona.setObjectName("pbSeleciona")
        self.verticalLayout_3.addWidget(self.pbSeleciona)
        self.pbCancela = QtWidgets.QPushButton(self.frSideButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCancela.sizePolicy().hasHeightForWidth())
        self.pbCancela.setSizePolicy(sizePolicy)
        self.pbCancela.setMinimumSize(QtCore.QSize(0, 0))
        self.pbCancela.setMaximumSize(QtCore.QSize(987987, 989849))
        self.pbCancela.setObjectName("pbCancela")
        self.verticalLayout_3.addWidget(self.pbCancela)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.gridLayout.addWidget(self.frSideButtons, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.frMain)
        mwBuscaProcessos.setCentralWidget(self.centralwidget)

        self.retranslateUi(mwBuscaProcessos)
        QtCore.QMetaObject.connectSlotsByName(mwBuscaProcessos)

    def retranslateUi(self, mwBuscaProcessos):
        _translate = QtCore.QCoreApplication.translate
        mwBuscaProcessos.setWindowTitle(_translate("mwBuscaProcessos", "MainWindow"))
        item = self.tblListaProcessos.horizontalHeaderItem(0)
        item.setText(_translate("mwBuscaProcessos", "Cód. Processo"))
        item = self.tblListaProcessos.horizontalHeaderItem(1)
        item.setText(_translate("mwBuscaProcessos", "Tipo do processo"))
        item = self.tblListaProcessos.horizontalHeaderItem(2)
        item.setText(_translate("mwBuscaProcessos", "Tipo do benefício"))
        item = self.tblListaProcessos.horizontalHeaderItem(3)
        item.setText(_translate("mwBuscaProcessos", "DER"))
        item = self.tblListaProcessos.horizontalHeaderItem(4)
        item.setText(_translate("mwBuscaProcessos", "Última atualização"))
        self.lbTitulo.setText(_translate("mwBuscaProcessos", "Buscar Processos"))
        self.lbSubtitulo.setText(_translate("mwBuscaProcessos", "Buscar processos do cliente selecionado."))
        self.lbInfoTelefone.setText(_translate("mwBuscaProcessos", "Tel/Cel:"))
        self.lbInfoEmail.setText(_translate("mwBuscaProcessos", "E-mail:"))
        self.lbEmail.setText(_translate("mwBuscaProcessos", "-"))
        self.lbTelefone.setText(_translate("mwBuscaProcessos", "-"))
        self.lbNomeCompleto.setText(_translate("mwBuscaProcessos", "Nome completo do cliente"))
        self.pbSeleciona.setText(_translate("mwBuscaProcessos", "Seleciona"))
        self.pbCancela.setText(_translate("mwBuscaProcessos", "Cancela"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mwBuscaProcessos = QtWidgets.QMainWindow()
    ui = Ui_mwBuscaProcessos()
    ui.setupUi(mwBuscaProcessos)
    mwBuscaProcessos.show()
    sys.exit(app.exec_())
