# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design/UI/cardIncidenteProcessual.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgIncidenteProcessual(object):
    def setupUi(self, wdgIncidenteProcessual):
        wdgIncidenteProcessual.setObjectName("wdgIncidenteProcessual")
        wdgIncidenteProcessual.resize(400, 135)
        self.gridLayout = QtWidgets.QGridLayout(wdgIncidenteProcessual)
        self.gridLayout.setObjectName("gridLayout")
        self.frMain = QtWidgets.QFrame(wdgIncidenteProcessual)
        self.frMain.setStyleSheet("/* ----------------- Line ---------------- */\n"
"#lnConexao{\n"
"    color: #566BBF;\n"
"}\n"
"\n"
"#lnSeparador {\n"
"    color: lightgrey;\n"
"}\n"
"\n"
"/* ------------------ Frame ----------------- */\n"
"#frInfoEsquerda, #frDescricao {\n"
"    background-color: #F9F9F9;\n"
"    border: 0px solid trasnparent;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#frFirulaCentral {\n"
"    background-color: #566BBF;\n"
"    border: 0px solid transparent;\n"
"    border-radius: 14px;\n"
"}\n"
"\n"
"/* -------------------- Label ------------------ */\n"
"#lbSeq {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: white;\n"
"    font-weight: 750;\n"
"}\n"
"\n"
"#lbAndamento {\n"
"    font: 10pt \"Avenir LT Std\";\n"
"    color: #566BBF;\n"
"}\n"
"\n"
"#lbDescricao {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: #3D464D;\n"
"}\n"
"\n"
"#lbDataIncidente {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: #566BBF;\n"
"    font-weight: 750;\n"
"}")
        self.frMain.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frMain.setObjectName("frMain")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frMain)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lnConexao = QtWidgets.QFrame(self.frMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnConexao.sizePolicy().hasHeightForWidth())
        self.lnConexao.setSizePolicy(sizePolicy)
        self.lnConexao.setMinimumSize(QtCore.QSize(30, 0))
        self.lnConexao.setMaximumSize(QtCore.QSize(15654887, 16777215))
        self.lnConexao.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lnConexao.setLineWidth(2)
        self.lnConexao.setFrameShape(QtWidgets.QFrame.HLine)
        self.lnConexao.setObjectName("lnConexao")
        self.gridLayout_3.addWidget(self.lnConexao, 4, 1, 1, 1)
        self.frInfoEsquerda = QtWidgets.QFrame(self.frMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frInfoEsquerda.sizePolicy().hasHeightForWidth())
        self.frInfoEsquerda.setSizePolicy(sizePolicy)
        self.frInfoEsquerda.setMinimumSize(QtCore.QSize(80, 80))
        self.frInfoEsquerda.setMaximumSize(QtCore.QSize(180, 80))
        self.frInfoEsquerda.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frInfoEsquerda.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoEsquerda.setObjectName("frInfoEsquerda")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frInfoEsquerda)
        self.gridLayout_2.setContentsMargins(4, 8, 4, 2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frFirulaCentral = QtWidgets.QFrame(self.frInfoEsquerda)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frFirulaCentral.sizePolicy().hasHeightForWidth())
        self.frFirulaCentral.setSizePolicy(sizePolicy)
        self.frFirulaCentral.setMinimumSize(QtCore.QSize(30, 30))
        self.frFirulaCentral.setMaximumSize(QtCore.QSize(30, 30))
        self.frFirulaCentral.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frFirulaCentral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frFirulaCentral.setObjectName("frFirulaCentral")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frFirulaCentral)
        self.horizontalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbSeq = QtWidgets.QLabel(self.frFirulaCentral)
        self.lbSeq.setAlignment(QtCore.Qt.AlignCenter)
        self.lbSeq.setObjectName("lbSeq")
        self.horizontalLayout_2.addWidget(self.lbSeq)
        self.gridLayout_2.addWidget(self.frFirulaCentral, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbAndamento = QtWidgets.QLabel(self.frInfoEsquerda)
        self.lbAndamento.setAlignment(QtCore.Qt.AlignCenter)
        self.lbAndamento.setObjectName("lbAndamento")
        self.gridLayout_2.addWidget(self.lbAndamento, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frInfoEsquerda, 4, 0, 1, 1)
        self.frDescricao = QtWidgets.QFrame(self.frMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frDescricao.sizePolicy().hasHeightForWidth())
        self.frDescricao.setSizePolicy(sizePolicy)
        self.frDescricao.setMinimumSize(QtCore.QSize(0, 80))
        self.frDescricao.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frDescricao.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frDescricao.setObjectName("frDescricao")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frDescricao)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbDescricao = QtWidgets.QLabel(self.frDescricao)
        self.lbDescricao.setScaledContents(True)
        self.lbDescricao.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbDescricao.setWordWrap(True)
        self.lbDescricao.setObjectName("lbDescricao")
        self.verticalLayout.addWidget(self.lbDescricao)
        self.gridLayout_3.addWidget(self.frDescricao, 4, 2, 1, 1)
        self.lnSeparador = QtWidgets.QFrame(self.frMain)
        self.lnSeparador.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lnSeparador.setLineWidth(2)
        self.lnSeparador.setFrameShape(QtWidgets.QFrame.HLine)
        self.lnSeparador.setObjectName("lnSeparador")
        self.gridLayout_3.addWidget(self.lnSeparador, 2, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 3)
        self.lbDataIncidente = QtWidgets.QLabel(self.frMain)
        self.lbDataIncidente.setObjectName("lbDataIncidente")
        self.gridLayout_3.addWidget(self.lbDataIncidente, 1, 0, 1, 3)
        self.gridLayout.addWidget(self.frMain, 0, 0, 1, 1)

        self.retranslateUi(wdgIncidenteProcessual)
        QtCore.QMetaObject.connectSlotsByName(wdgIncidenteProcessual)

    def retranslateUi(self, wdgIncidenteProcessual):
        _translate = QtCore.QCoreApplication.translate
        wdgIncidenteProcessual.setWindowTitle(_translate("wdgIncidenteProcessual", "Form"))
        self.lbSeq.setText(_translate("wdgIncidenteProcessual", "1"))
        self.lbAndamento.setText(_translate("wdgIncidenteProcessual", "Andamento"))
        self.lbDescricao.setText(_translate("wdgIncidenteProcessual", "TextLabel"))
        self.lbDataIncidente.setText(_translate("wdgIncidenteProcessual", "25 de Maio de 2021"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgIncidenteProcessual = QtWidgets.QWidget()
    ui = Ui_wdgIncidenteProcessual()
    ui.setupUi(wdgIncidenteProcessual)
    wdgIncidenteProcessual.show()
    sys.exit(app.exec_())
