# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design/UI/menuFiltroContrib.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgNewMenu(object):
    def setupUi(self, wdgNewMenu):
        wdgNewMenu.setObjectName("wdgNewMenu")
        wdgNewMenu.resize(191, 457)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wdgNewMenu.sizePolicy().hasHeightForWidth())
        wdgNewMenu.setSizePolicy(sizePolicy)
        wdgNewMenu.setMinimumSize(QtCore.QSize(191, 457))
        wdgNewMenu.setStyleSheet("/*------------------------------------ Frame ------------------------------------*/\n"
"#frMenu {\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"    border-style: solid;\n"
"    border-color: lightgrey;\n"
"    border-width: 1px;\n"
"}\n"
"\n"
"#frSeparador {\n"
"    background-color: lightgrey;\n"
"}\n"
"\n"
"#frBusca {\n"
"    border-radius: 4px;\n"
"    border: 1px solid lightgrey;\n"
"}\n"
"\n"
"/*------------------------------------ Label ------------------------------------*/\n"
"#lbTitulo {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 16px;\n"
"    font-weight: 300;\n"
"}\n"
"\n"
"#lbData, #lbIndicadores {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#lbInfoDe, #lbInfoAte {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#lbInfoBusca {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"\n"
"    margin-top: 4px;\n"
"}\n"
"\n"
"/*------------------------------------ Line Edit ------------------------------------*/\n"
"\n"
"#leBusca {\n"
"    border: 0px solid transparent;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(wdgNewMenu)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frMenu = QtWidgets.QFrame(wdgNewMenu)
        self.frMenu.setMinimumSize(QtCore.QSize(0, 0))
        self.frMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frMenu.setObjectName("frMenu")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frMenu)
        self.gridLayout_3.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frBusca = QtWidgets.QFrame(self.frMenu)
        self.frBusca.setMinimumSize(QtCore.QSize(0, 30))
        self.frBusca.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frBusca.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frBusca.setObjectName("frBusca")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frBusca)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbInfoBusca = QtWidgets.QLabel(self.frBusca)
        self.lbInfoBusca.setObjectName("lbInfoBusca")
        self.horizontalLayout.addWidget(self.lbInfoBusca)
        self.leBusca = QtWidgets.QLineEdit(self.frBusca)
        self.leBusca.setInputMask("")
        self.leBusca.setMaxLength(30)
        self.leBusca.setObjectName("leBusca")
        self.horizontalLayout.addWidget(self.leBusca)
        self.gridLayout_3.addWidget(self.frBusca, 7, 0, 1, 1)
        self.frSeparador = QtWidgets.QFrame(self.frMenu)
        self.frSeparador.setMinimumSize(QtCore.QSize(0, 2))
        self.frSeparador.setMaximumSize(QtCore.QSize(16777215, 2))
        self.frSeparador.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frSeparador.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frSeparador.setObjectName("frSeparador")
        self.gridLayout_3.addWidget(self.frSeparador, 1, 0, 1, 1)
        self.frSeparador2 = QtWidgets.QFrame(self.frMenu)
        self.frSeparador2.setMinimumSize(QtCore.QSize(0, 2))
        self.frSeparador2.setMaximumSize(QtCore.QSize(16777215, 2))
        self.frSeparador2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frSeparador2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frSeparador2.setObjectName("frSeparador2")
        self.gridLayout_3.addWidget(self.frSeparador2, 5, 0, 1, 1)
        self.frData = QtWidgets.QFrame(self.frMenu)
        self.frData.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frData.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frData.setObjectName("frData")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frData)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbInfoDe = QtWidgets.QLabel(self.frData)
        self.lbInfoDe.setObjectName("lbInfoDe")
        self.gridLayout_2.addWidget(self.lbInfoDe, 0, 0, 1, 1)
        self.dtDe = QtWidgets.QDateEdit(self.frData)
        self.dtDe.setCalendarPopup(True)
        self.dtDe.setObjectName("dtDe")
        self.gridLayout_2.addWidget(self.dtDe, 0, 1, 1, 1)
        self.lbInfoAte = QtWidgets.QLabel(self.frData)
        self.lbInfoAte.setObjectName("lbInfoAte")
        self.gridLayout_2.addWidget(self.lbInfoAte, 1, 0, 1, 1)
        self.dtAte = QtWidgets.QDateEdit(self.frData)
        self.dtAte.setCalendarPopup(True)
        self.dtAte.setObjectName("dtAte")
        self.gridLayout_2.addWidget(self.dtAte, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frData, 4, 0, 1, 1)
        self.lbTitulo = QtWidgets.QLabel(self.frMenu)
        self.lbTitulo.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lbTitulo.setObjectName("lbTitulo")
        self.gridLayout_3.addWidget(self.lbTitulo, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.frMenu)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 200))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 171, 198))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vlIndicadores = QtWidgets.QVBoxLayout()
        self.vlIndicadores.setContentsMargins(-1, -1, -1, 4)
        self.vlIndicadores.setObjectName("vlIndicadores")
        self.verticalLayout.addLayout(self.vlIndicadores)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 8, 0, 1, 1)
        self.lbData = QtWidgets.QLabel(self.frMenu)
        self.lbData.setObjectName("lbData")
        self.gridLayout_3.addWidget(self.lbData, 3, 0, 1, 1)
        self.lbIndicadores = QtWidgets.QLabel(self.frMenu)
        self.lbIndicadores.setObjectName("lbIndicadores")
        self.gridLayout_3.addWidget(self.lbIndicadores, 6, 0, 1, 1)
        self.frSeparador1 = QtWidgets.QFrame(self.frMenu)
        self.frSeparador1.setMinimumSize(QtCore.QSize(0, 2))
        self.frSeparador1.setMaximumSize(QtCore.QSize(16777215, 2))
        self.frSeparador1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frSeparador1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frSeparador1.setObjectName("frSeparador1")
        self.gridLayout_3.addWidget(self.frSeparador1, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frMenu, 0, 0, 1, 1)

        self.retranslateUi(wdgNewMenu)
        QtCore.QMetaObject.connectSlotsByName(wdgNewMenu)

    def retranslateUi(self, wdgNewMenu):
        _translate = QtCore.QCoreApplication.translate
        wdgNewMenu.setWindowTitle(_translate("wdgNewMenu", "Form"))
        self.lbInfoBusca.setText(_translate("wdgNewMenu", "Busca:"))
        self.leBusca.setPlaceholderText(_translate("wdgNewMenu", "Indicador"))
        self.lbInfoDe.setText(_translate("wdgNewMenu", "De:"))
        self.lbInfoAte.setText(_translate("wdgNewMenu", "Até:"))
        self.lbTitulo.setText(_translate("wdgNewMenu", "Filtros"))
        self.lbData.setText(_translate("wdgNewMenu", "Data"))
        self.lbIndicadores.setText(_translate("wdgNewMenu", "Indicadores"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgNewMenu = QtWidgets.QWidget()
    ui = Ui_wdgNewMenu()
    ui.setupUi(wdgNewMenu)
    wdgNewMenu.show()
    sys.exit(app.exec_())
