# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design/UI/newDashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newDashboard(object):
    def setupUi(self, newDashboard):
        newDashboard.setObjectName("newDashboard")
        newDashboard.resize(1259, 576)
        newDashboard.setDockNestingEnabled(True)
        self.frMain = QtWidgets.QWidget(newDashboard)
        self.frMain.setStyleSheet("/*-------------------------------------------------- Frames --------------------------------------------------*/\n"
"#frCabecalho {\n"
"    background-color: #3F4E8C;\n"
"}\n"
"\n"
"#frBottom {\n"
"    background-color: #3A405A;\n"
"}\n"
"\n"
"#frAvatar {\n"
"    background-color: #3F64FF;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"/*-------------------------------------------------- Labels --------------------------------------------------*/\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"\n"
"#lbNomeEscritorio {\n"
"    font: 24pt \"Bebas Neue\";\n"
"}\n"
"\n"
"#lbNomeAdvogado {\n"
"    font: 10pt \"Avenir LT Std\";\n"
"}\n"
"\n"
"#lbOAB {\n"
"    font: 8pt \"Avenir LT Std\";\n"
"    font-weight: 750;\n"
"}\n"
"\n"
"/*-------------------------------------------------- Push Buttom --------------------------------------------------*/\n"
"#pbMenuPrincipal {\n"
"    background-color: #292D40;\n"
"    border: 0px solid transparent;\n"
"    border-radius: 21px;\n"
"    \n"
"    background-image: url(:/menuPrincipal/hamburger.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}\n"
"\n"
"#pbAvisos {\n"
"    background-color: transparent;\n"
"\n"
"    background-image: url(:/menuPrincipal/avisos.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}\n"
"\n"
"/*-------------------------------------------------- Stacked Eidget --------------------------------------------------*/\n"
"#stkPrincipal {\n"
"    background-color: white;\n"
"}")
        self.frMain.setObjectName("frMain")
        self.gridLayout = QtWidgets.QGridLayout(self.frMain)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frCenter = QtWidgets.QFrame(self.frMain)
        self.frCenter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frCenter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frCenter.setObjectName("frCenter")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frCenter)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frCabecalho = QtWidgets.QFrame(self.frCenter)
        self.frCabecalho.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frCabecalho.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frCabecalho.setObjectName("frCabecalho")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frCabecalho)
        self.horizontalLayout.setContentsMargins(16, 8, 16, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frInfoAdv = QtWidgets.QFrame(self.frCabecalho)
        self.frInfoAdv.setMaximumSize(QtCore.QSize(230, 16777215))
        self.frInfoAdv.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frInfoAdv.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoAdv.setObjectName("frInfoAdv")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frInfoAdv)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frAvatar = QtWidgets.QFrame(self.frInfoAdv)
        self.frAvatar.setMinimumSize(QtCore.QSize(40, 40))
        self.frAvatar.setMaximumSize(QtCore.QSize(40, 40))
        self.frAvatar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frAvatar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frAvatar.setObjectName("frAvatar")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frAvatar)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.frAvatar)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout_2.addWidget(self.frAvatar, 0, 0, 2, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbNomeAdvogado = QtWidgets.QLabel(self.frInfoAdv)
        self.lbNomeAdvogado.setObjectName("lbNomeAdvogado")
        self.gridLayout_2.addWidget(self.lbNomeAdvogado, 0, 1, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.lbOAB = QtWidgets.QLabel(self.frInfoAdv)
        self.lbOAB.setObjectName("lbOAB")
        self.gridLayout_2.addWidget(self.lbOAB, 1, 1, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.frInfoAdv, 0, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lbNomeEscritorio = QtWidgets.QLabel(self.frCabecalho)
        self.lbNomeEscritorio.setObjectName("lbNomeEscritorio")
        self.horizontalLayout.addWidget(self.lbNomeEscritorio, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pbAvisos = QtWidgets.QPushButton(self.frCabecalho)
        self.pbAvisos.setText("")
        self.pbAvisos.setObjectName("pbAvisos")
        self.horizontalLayout.addWidget(self.pbAvisos)
        self.pbMenuPrincipal = QtWidgets.QPushButton(self.frCabecalho)
        self.pbMenuPrincipal.setMinimumSize(QtCore.QSize(42, 42))
        self.pbMenuPrincipal.setMaximumSize(QtCore.QSize(42, 42))
        self.pbMenuPrincipal.setText("")
        self.pbMenuPrincipal.setObjectName("pbMenuPrincipal")
        self.horizontalLayout.addWidget(self.pbMenuPrincipal)
        self.verticalLayout.addWidget(self.frCabecalho)
        self.frConteudo = QtWidgets.QFrame(self.frCenter)
        self.frConteudo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frConteudo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frConteudo.setObjectName("frConteudo")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frConteudo)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stkPrincipal = QtWidgets.QStackedWidget(self.frConteudo)
        self.stkPrincipal.setObjectName("stkPrincipal")
        self.gridLayout_3.addWidget(self.stkPrincipal, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frConteudo)
        self.frBottom = QtWidgets.QFrame(self.frCenter)
        self.frBottom.setMinimumSize(QtCore.QSize(0, 30))
        self.frBottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frBottom.setObjectName("frBottom")
        self.verticalLayout.addWidget(self.frBottom)
        self.gridLayout.addWidget(self.frCenter, 0, 0, 1, 1)
        newDashboard.setCentralWidget(self.frMain)

        self.retranslateUi(newDashboard)
        QtCore.QMetaObject.connectSlotsByName(newDashboard)

    def retranslateUi(self, newDashboard):
        _translate = QtCore.QCoreApplication.translate
        newDashboard.setWindowTitle(_translate("newDashboard", "MainWindow"))
        self.label.setText(_translate("newDashboard", "IA"))
        self.lbNomeAdvogado.setText(_translate("newDashboard", "Nome do Advogado"))
        self.lbOAB.setText(_translate("newDashboard", "OAB: 99999/SP"))
        self.lbNomeEscritorio.setText(_translate("newDashboard", "Dominária e associados"))
import Resources.newDashboard


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    newDashboard = QtWidgets.QMainWindow()
    ui = Ui_newDashboard()
    ui.setupUi(newDashboard)
    newDashboard.show()
    sys.exit(app.exec_())
