# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pgTipoBeneficioConc.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgTipoBeneficioConc(object):
    def setupUi(self, wdgTipoBeneficioConc):
        wdgTipoBeneficioConc.setObjectName("wdgTipoBeneficioConc")
        wdgTipoBeneficioConc.resize(891, 655)
        wdgTipoBeneficioConc.setStyleSheet("/* ------------------------------ Widgets ------------------------------ */\n"
"#wdgNatureza{\n"
"    background-color: transparent;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/* ------------------------------ Frames ------------------------------ */\n"
"#frMain{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 246, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/* ------------------------------ Labels ------------------------------ */\n"
"#lbTituloNatureza, #lbOu {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 24px;\n"
"\n"
"    color: grey;\n"
"}\n"
"\n"
"/* ------------------------------ Push Buttons ------------------------------ */\n"
"#pbAposentadoria, #pbAuxReclusao, #pbAuxilioDoenca, \n"
"#pbBeneDeficiencia, #pbBeneIdoso, #pbPensaoMorte, \n"
"#pbSalMaternidade {\n"
"    background-color: rgb(117, 80, 123);\n"
"    border-radius: 16px;\n"
"\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 24px;\n"
"    color: white;    \n"
"}\n"
"\n"
"#pbAposentadoria:hover, #pbAuxReclusao:hover, #pbAuxilioDoenca:hover, #pbBeneDeficiencia:hover, #pbBeneIdoso:hover, #pbPensaoMorte:hover, #pbSalMaternidade:hover {\n"
"    background-color: rgb(115, 210, 22);\n"
"    border-radius: 16px;\n"
"\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 24px;\n"
"    color: white;    \n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(wdgTipoBeneficioConc)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frMain = QtWidgets.QFrame(wdgTipoBeneficioConc)
        self.frMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frMain.setObjectName("frMain")
        self.gridLayout = QtWidgets.QGridLayout(self.frMain)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.frMain)
        self.frame_2.setMaximumSize(QtCore.QSize(16777214, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbTituloNatureza = QtWidgets.QLabel(self.frame_2)
        self.lbTituloNatureza.setObjectName("lbTituloNatureza")
        self.horizontalLayout.addWidget(self.lbTituloNatureza)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frMain)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.pbAposentadoria = QtWidgets.QPushButton(self.frame)
        self.pbAposentadoria.setMinimumSize(QtCore.QSize(350, 80))
        self.pbAposentadoria.setMaximumSize(QtCore.QSize(350, 80))
        self.pbAposentadoria.setObjectName("pbAposentadoria")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pbAposentadoria)
        self.pbAuxReclusao = QtWidgets.QPushButton(self.frame)
        self.pbAuxReclusao.setMinimumSize(QtCore.QSize(350, 80))
        self.pbAuxReclusao.setMaximumSize(QtCore.QSize(350, 80))
        self.pbAuxReclusao.setObjectName("pbAuxReclusao")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pbAuxReclusao)
        self.pbBeneIdoso = QtWidgets.QPushButton(self.frame)
        self.pbBeneIdoso.setMinimumSize(QtCore.QSize(350, 80))
        self.pbBeneIdoso.setMaximumSize(QtCore.QSize(350, 80))
        self.pbBeneIdoso.setObjectName("pbBeneIdoso")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pbBeneIdoso)
        self.pbBeneDeficiencia = QtWidgets.QPushButton(self.frame)
        self.pbBeneDeficiencia.setMinimumSize(QtCore.QSize(350, 80))
        self.pbBeneDeficiencia.setMaximumSize(QtCore.QSize(350, 80))
        self.pbBeneDeficiencia.setObjectName("pbBeneDeficiencia")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pbBeneDeficiencia)
        self.pbSalMaternidade = QtWidgets.QPushButton(self.frame)
        self.pbSalMaternidade.setMinimumSize(QtCore.QSize(350, 80))
        self.pbSalMaternidade.setMaximumSize(QtCore.QSize(350, 80))
        self.pbSalMaternidade.setObjectName("pbSalMaternidade")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pbSalMaternidade)
        self.pbAuxilioDoenca = QtWidgets.QPushButton(self.frame)
        self.pbAuxilioDoenca.setMinimumSize(QtCore.QSize(350, 80))
        self.pbAuxilioDoenca.setMaximumSize(QtCore.QSize(350, 80))
        self.pbAuxilioDoenca.setObjectName("pbAuxilioDoenca")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pbAuxilioDoenca)
        self.pbPensaoMorte = QtWidgets.QPushButton(self.frame)
        self.pbPensaoMorte.setMinimumSize(QtCore.QSize(350, 80))
        self.pbPensaoMorte.setMaximumSize(QtCore.QSize(350, 80))
        self.pbPensaoMorte.setObjectName("pbPensaoMorte")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pbPensaoMorte)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.frMain)

        self.retranslateUi(wdgTipoBeneficioConc)
        QtCore.QMetaObject.connectSlotsByName(wdgTipoBeneficioConc)

    def retranslateUi(self, wdgTipoBeneficioConc):
        _translate = QtCore.QCoreApplication.translate
        wdgTipoBeneficioConc.setWindowTitle(_translate("wdgTipoBeneficioConc", "Form"))
        self.lbTituloNatureza.setText(_translate("wdgTipoBeneficioConc", "Escolha o tipo de benefício"))
        self.pbAposentadoria.setText(_translate("wdgTipoBeneficioConc", "Aposentadoria"))
        self.pbAuxReclusao.setText(_translate("wdgTipoBeneficioConc", "Auxílio \n"
"reclusão"))
        self.pbBeneIdoso.setText(_translate("wdgTipoBeneficioConc", "Benefício assistencial \n"
"ao idoso"))
        self.pbBeneDeficiencia.setText(_translate("wdgTipoBeneficioConc", "Benefício assistencial à \n"
"pessoa com deficiência"))
        self.pbSalMaternidade.setText(_translate("wdgTipoBeneficioConc", "Salário maternidade"))
        self.pbAuxilioDoenca.setText(_translate("wdgTipoBeneficioConc", "Auxílio \n"
"doença"))
        self.pbPensaoMorte.setText(_translate("wdgTipoBeneficioConc", "Pensão por morte"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgTipoBeneficioConc = QtWidgets.QWidget()
    ui = Ui_wdgTipoBeneficioConc()
    ui.setupUi(wdgTipoBeneficioConc)
    wdgTipoBeneficioConc.show()
    sys.exit(app.exec_())
