# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design/UI/processoPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgProcessoPage(object):
    def setupUi(self, wdgProcessoPage):
        wdgProcessoPage.setObjectName("wdgProcessoPage")
        wdgProcessoPage.resize(1148, 637)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wdgProcessoPage.sizePolicy().hasHeightForWidth())
        wdgProcessoPage.setSizePolicy(sizePolicy)
        wdgProcessoPage.setMinimumSize(QtCore.QSize(0, 0))
        wdgProcessoPage.setMaximumSize(QtCore.QSize(16777215, 15498465))
        wdgProcessoPage.setStyleSheet("#wdgCadastroCliente {\n"
"    background-color: white;\n"
"}\n"
"\n"
"#frCabecalho, #frMiolo, #frRodape {\n"
"    background-color: white;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(wdgProcessoPage)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frPeticao = QtWidgets.QFrame(wdgProcessoPage)
        self.frPeticao.setStyleSheet("/* ---------- Frame ---------- */\n"
"#frDocView{\n"
"    background-color: white;\n"
"}\n"
"\n"
"#frOpcoesEdicao {\n"
"    background-color: white;\n"
"    border: 1px solid lightgrey;\n"
"\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"#frPeticao {\n"
"    background-color: white;\n"
"}\n"
"\n"
"#frDocumento {\n"
"    background-color: lightgrey;\n"
"}\n"
"\n"
"/* ---------- Push button ---------- */\n"
"#pbOpImprimir {\n"
"    background-image: url(:/documentos/impressora_blue.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"\n"
"    background-color: transparent;\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"#pbFull {\n"
"    background-image: url(:/documentos/Maximize.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"\n"
"    background-color: transparent;\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"#pbZoomIn {\n"
"    background-image: url(:/documentos/zoomIn.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"\n"
"    background-color: transparent;\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"#pbZoomOut {\n"
"    background-image: url(:/documentos/zoomOut.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"\n"
"    background-color: transparent;\n"
"    border: 0px solid transparent;\n"
"}")
        self.frPeticao.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frPeticao.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frPeticao.setObjectName("frPeticao")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frPeticao)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frDocumento = QtWidgets.QFrame(self.frPeticao)
        self.frDocumento.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frDocumento.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frDocumento.setObjectName("frDocumento")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frDocumento)
        self.verticalLayout_2.setSpacing(24)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frDocView = QtWidgets.QFrame(self.frDocumento)
        self.frDocView.setMinimumSize(QtCore.QSize(380, 0))
        self.frDocView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frDocView.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frDocView.setObjectName("frDocView")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frDocView)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 533, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frDocView)
        self.frOpcoesEdicao = QtWidgets.QFrame(self.frDocumento)
        self.frOpcoesEdicao.setMinimumSize(QtCore.QSize(180, 0))
        self.frOpcoesEdicao.setMaximumSize(QtCore.QSize(180, 12321546))
        self.frOpcoesEdicao.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frOpcoesEdicao.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frOpcoesEdicao.setObjectName("frOpcoesEdicao")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frOpcoesEdicao)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pbOpImprimir = QtWidgets.QPushButton(self.frOpcoesEdicao)
        self.pbOpImprimir.setMinimumSize(QtCore.QSize(24, 24))
        self.pbOpImprimir.setMaximumSize(QtCore.QSize(24, 24))
        self.pbOpImprimir.setText("")
        self.pbOpImprimir.setObjectName("pbOpImprimir")
        self.horizontalLayout_9.addWidget(self.pbOpImprimir)
        self.line = QtWidgets.QFrame(self.frOpcoesEdicao)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout_9.addWidget(self.line)
        self.pbZoomIn = QtWidgets.QPushButton(self.frOpcoesEdicao)
        self.pbZoomIn.setMinimumSize(QtCore.QSize(24, 24))
        self.pbZoomIn.setMaximumSize(QtCore.QSize(24, 24))
        self.pbZoomIn.setText("")
        self.pbZoomIn.setObjectName("pbZoomIn")
        self.horizontalLayout_9.addWidget(self.pbZoomIn)
        self.pbZoomOut = QtWidgets.QPushButton(self.frOpcoesEdicao)
        self.pbZoomOut.setMinimumSize(QtCore.QSize(24, 24))
        self.pbZoomOut.setMaximumSize(QtCore.QSize(24, 24))
        self.pbZoomOut.setText("")
        self.pbZoomOut.setObjectName("pbZoomOut")
        self.horizontalLayout_9.addWidget(self.pbZoomOut)
        self.pbFull = QtWidgets.QPushButton(self.frOpcoesEdicao)
        self.pbFull.setMinimumSize(QtCore.QSize(24, 24))
        self.pbFull.setMaximumSize(QtCore.QSize(24, 24))
        self.pbFull.setText("")
        self.pbFull.setObjectName("pbFull")
        self.horizontalLayout_9.addWidget(self.pbFull)
        self.verticalLayout_2.addWidget(self.frOpcoesEdicao, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frDocumento)
        self.gridLayout.addWidget(self.frPeticao, 0, 1, 1, 1)
        self.frPrincipal = QtWidgets.QFrame(wdgProcessoPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frPrincipal.sizePolicy().hasHeightForWidth())
        self.frPrincipal.setSizePolicy(sizePolicy)
        self.frPrincipal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frPrincipal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frPrincipal.setObjectName("frPrincipal")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frPrincipal)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frCabecalho = QtWidgets.QFrame(self.frPrincipal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frCabecalho.sizePolicy().hasHeightForWidth())
        self.frCabecalho.setSizePolicy(sizePolicy)
        self.frCabecalho.setMinimumSize(QtCore.QSize(0, 80))
        self.frCabecalho.setMaximumSize(QtCore.QSize(16777215, 12354654))
        self.frCabecalho.setStyleSheet("/*------------------------------------------- Frame -------------------------------------------*/\n"
"#frPrimeiraEtapa {\n"
"    border-radius: 8px;\n"
"    background-color: #009E38;\n"
"}\n"
"\n"
"#frSegundaEtapa, #frTerceiraEtapa, \n"
"#frQuartaEtapa, #frQuintaEtapa {\n"
"    border-radius: 8px;\n"
"    background-color: #CFF2DC;\n"
"}\n"
"\n"
"#frSeparador1, #frSeparador2, #frSeparador3, #frSeparador4 {\n"
"    background-color: lightgrey;\n"
"}\n"
"\n"
"/*------------------------------------------- Push Button -------------------------------------------*/\n"
"#pbVoltar {\n"
"    background-image: url(:/voltar/back.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"\n"
"    background-color: #F4F5F8;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"#pbVoltar:hover {\n"
"    background-image: url(:/voltar/back.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"\n"
"    background-color: rgb(228, 233, 248);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"\n"
"/*------------------------------------------- Label -------------------------------------------*/\n"
"#lbInfoTitulo {\n"
"    font: 16pt \"Avenir LT Std\";\n"
"    color: #3F4E8C;\n"
"    font-weight: 750;\n"
"}\n"
"\n"
"#lbInfoNatureza, #lbInfoTpBeneficio,\n"
"#lbInfoTpProcesso, #lbInfoEntrevista {\n"
"    font: 10pt \"Avenir LT Std\";\n"
"    color: black;\n"
"    padding: 4px;\n"
"}")
        self.frCabecalho.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frCabecalho.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frCabecalho.setObjectName("frCabecalho")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frCabecalho)
        self.horizontalLayout.setContentsMargins(16, 0, 0, 0)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbVoltar = QtWidgets.QPushButton(self.frCabecalho)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbVoltar.sizePolicy().hasHeightForWidth())
        self.pbVoltar.setSizePolicy(sizePolicy)
        self.pbVoltar.setMinimumSize(QtCore.QSize(40, 40))
        self.pbVoltar.setMaximumSize(QtCore.QSize(40, 40))
        self.pbVoltar.setText("")
        self.pbVoltar.setObjectName("pbVoltar")
        self.horizontalLayout.addWidget(self.pbVoltar)
        self.lbInfoTitulo = QtWidgets.QLabel(self.frCabecalho)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbInfoTitulo.sizePolicy().hasHeightForWidth())
        self.lbInfoTitulo.setSizePolicy(sizePolicy)
        self.lbInfoTitulo.setObjectName("lbInfoTitulo")
        self.horizontalLayout.addWidget(self.lbInfoTitulo)
        self.verticalLayout.addWidget(self.frCabecalho)
        self.frMiolo = QtWidgets.QFrame(self.frPrincipal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frMiolo.sizePolicy().hasHeightForWidth())
        self.frMiolo.setSizePolicy(sizePolicy)
        self.frMiolo.setMinimumSize(QtCore.QSize(0, 0))
        self.frMiolo.setMaximumSize(QtCore.QSize(16777215, 16546878))
        self.frMiolo.setStyleSheet("/* -------- Geral --------- */\n"
"QCheckBox {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: #040D14;\n"
"\n"
"    font-weight: 150;\n"
"    margin: 0px 12px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(:/checkbox/CheckBoxFalse.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/checkbox/checkBoxTrue.png);\n"
"}\n"
"\n"
"/* --------  Push Button -------- */\n"
"#pbGeraPdf {\n"
"    background-image: url(:/documentos/documento.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"\n"
"    background-color: transparent;\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"#pbImprimir {\n"
"    background-image: url(:/documentos/impressora_blue.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"\n"
"    background-color: transparent;\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"#pbBuscarCliente {\n"
"    background-color: white;\n"
"    border: 2px dashed #3F4E8C;\n"
"    border-radius: 4px;    \n"
"    \n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: #3F4E8C;\n"
"    font-weight: 750;\n"
"}\n"
"\n"
"/* ----------  Label -------- */\n"
"#lbNomeCliente, #lbClienteEmail,\n"
"#lbClienteTelefone {\n"
"    font: 10pt \"Avenir LT Std\";\n"
"    color: #040D14;\n"
"    font-weight: 200;\n"
"}\n"
"\n"
"#lbInfoNumProcesso, #lbInfoTituloDocs {\n"
"    font: 16pt \"Avenir LT Std\";\n"
"    color: #3F4E8C;\n"
"    font-weight: 750;\n"
"}\n"
"\n"
"#lbNumProcesso {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: #3A405A;\n"
"}\n"
"\n"
"#lbInfoNatureza, #lbInfoTpBeneficio,\n"
"#lbInfoTpProcesso {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: #3A405A;\n"
"    font-weight: 750;\n"
"}\n"
"\n"
"#lbNatureza, #lbTpBeneficio,\n"
"#lbTpProcesso, #lbInfoDescricao {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: #3A405A;\n"
"    font-weight: 200;\n"
"}\n"
"\n"
"#lbInfoImprimir, #lbInfoGeraPdf {\n"
"    font: 10pt \"Avenir LT Std\";\n"
"    color: #3A405A;\n"
"}\n"
"\n"
"#lbTituloListaProcessos {\n"
"    font: 14pt \"Avenir LT Std\";\n"
"    color: white;\n"
"    font-weight: 750;\n"
"}\n"
"\n"
"/* ------------------------------------ Frames ------------------------------------*/\n"
"#frInfoProcSelecionado {\n"
"    background-color: #F9F9F9;\n"
"    border: 0px solid none;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"#frBotoesDocs {\n"
"    background-color: transparent;\n"
"    border: 1px solid transparent;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"#frBuscaCliente {\n"
"    background-color: white;\n"
"}\n"
"\n"
"#frFirulaProcesso {\n"
"    background-color: #009E38;\n"
"    border: 0px solid transparent;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"#frTituloListaProcessos{\n"
"    background-color: #3F4E8C;\n"
"    border: 0px solid transparent;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/*---------------------------- Scroll Area ----------------------------------*/\n"
"#frInfoGeralProcesso {\n"
"    background-color: white;\n"
"}\n"
"")
        self.frMiolo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frMiolo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frMiolo.setObjectName("frMiolo")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frMiolo)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frEsquerda = QtWidgets.QFrame(self.frMiolo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frEsquerda.sizePolicy().hasHeightForWidth())
        self.frEsquerda.setSizePolicy(sizePolicy)
        self.frEsquerda.setMinimumSize(QtCore.QSize(350, 0))
        self.frEsquerda.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frEsquerda.setStyleSheet("")
        self.frEsquerda.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frEsquerda.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frEsquerda.setObjectName("frEsquerda")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frEsquerda)
        self.gridLayout_3.setContentsMargins(12, 2, 2, 2)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stkInfoCliente = QtWidgets.QStackedWidget(self.frEsquerda)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stkInfoCliente.sizePolicy().hasHeightForWidth())
        self.stkInfoCliente.setSizePolicy(sizePolicy)
        self.stkInfoCliente.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stkInfoCliente.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stkInfoCliente.setObjectName("stkInfoCliente")
        self.frBuscaCliente = QtWidgets.QWidget()
        self.frBuscaCliente.setObjectName("frBuscaCliente")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frBuscaCliente)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pbBuscarCliente = QtWidgets.QPushButton(self.frBuscaCliente)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbBuscarCliente.sizePolicy().hasHeightForWidth())
        self.pbBuscarCliente.setSizePolicy(sizePolicy)
        self.pbBuscarCliente.setObjectName("pbBuscarCliente")
        self.verticalLayout_7.addWidget(self.pbBuscarCliente)
        self.stkInfoCliente.addWidget(self.frBuscaCliente)
        self.frClienteSelecionado = QtWidgets.QWidget()
        self.frClienteSelecionado.setObjectName("frClienteSelecionado")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frClienteSelecionado)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.frClienteSelecionado)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbClienteFoto = QtWidgets.QLabel(self.frame_4)
        self.lbClienteFoto.setObjectName("lbClienteFoto")
        self.horizontalLayout_6.addWidget(self.lbClienteFoto)
        self.horizontalLayout_5.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frClienteSelecionado)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbNomeCliente = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbNomeCliente.sizePolicy().hasHeightForWidth())
        self.lbNomeCliente.setSizePolicy(sizePolicy)
        self.lbNomeCliente.setObjectName("lbNomeCliente")
        self.verticalLayout_5.addWidget(self.lbNomeCliente)
        self.lbClienteTelefone = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbClienteTelefone.sizePolicy().hasHeightForWidth())
        self.lbClienteTelefone.setSizePolicy(sizePolicy)
        self.lbClienteTelefone.setObjectName("lbClienteTelefone")
        self.verticalLayout_5.addWidget(self.lbClienteTelefone)
        self.lbClienteEmail = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbClienteEmail.sizePolicy().hasHeightForWidth())
        self.lbClienteEmail.setSizePolicy(sizePolicy)
        self.lbClienteEmail.setObjectName("lbClienteEmail")
        self.verticalLayout_5.addWidget(self.lbClienteEmail)
        self.horizontalLayout_5.addWidget(self.frame_5)
        self.stkInfoCliente.addWidget(self.frClienteSelecionado)
        self.gridLayout_3.addWidget(self.stkInfoCliente, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        self.frInfoGeralProcessos = QtWidgets.QFrame(self.frEsquerda)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frInfoGeralProcessos.sizePolicy().hasHeightForWidth())
        self.frInfoGeralProcessos.setSizePolicy(sizePolicy)
        self.frInfoGeralProcessos.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frInfoGeralProcessos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoGeralProcessos.setObjectName("frInfoGeralProcessos")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frInfoGeralProcessos)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(12)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frInfoProcSelecionado = QtWidgets.QFrame(self.frInfoGeralProcessos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frInfoProcSelecionado.sizePolicy().hasHeightForWidth())
        self.frInfoProcSelecionado.setSizePolicy(sizePolicy)
        self.frInfoProcSelecionado.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frInfoProcSelecionado.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoProcSelecionado.setObjectName("frInfoProcSelecionado")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frInfoProcSelecionado)
        self.gridLayout_2.setVerticalSpacing(12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frInfosProc = QtWidgets.QFrame(self.frInfoProcSelecionado)
        self.frInfosProc.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frInfosProc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfosProc.setObjectName("frInfosProc")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frInfosProc)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setVerticalSpacing(8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbTpBeneficio = QtWidgets.QLabel(self.frInfosProc)
        self.lbTpBeneficio.setObjectName("lbTpBeneficio")
        self.gridLayout_4.addWidget(self.lbTpBeneficio, 1, 1, 1, 1)
        self.lbInfoTpBeneficio = QtWidgets.QLabel(self.frInfosProc)
        self.lbInfoTpBeneficio.setObjectName("lbInfoTpBeneficio")
        self.gridLayout_4.addWidget(self.lbInfoTpBeneficio, 1, 0, 1, 1)
        self.lbNatureza = QtWidgets.QLabel(self.frInfosProc)
        self.lbNatureza.setObjectName("lbNatureza")
        self.gridLayout_4.addWidget(self.lbNatureza, 0, 1, 1, 1)
        self.lbInfoTpProcesso = QtWidgets.QLabel(self.frInfosProc)
        self.lbInfoTpProcesso.setObjectName("lbInfoTpProcesso")
        self.gridLayout_4.addWidget(self.lbInfoTpProcesso, 2, 0, 1, 1)
        self.lbInfoNatureza = QtWidgets.QLabel(self.frInfosProc)
        self.lbInfoNatureza.setObjectName("lbInfoNatureza")
        self.gridLayout_4.addWidget(self.lbInfoNatureza, 0, 0, 1, 1)
        self.lbTpProcesso = QtWidgets.QLabel(self.frInfosProc)
        self.lbTpProcesso.setObjectName("lbTpProcesso")
        self.gridLayout_4.addWidget(self.lbTpProcesso, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frInfosProc, 1, 1, 1, 1)
        self.frNumProcesso = QtWidgets.QFrame(self.frInfoProcSelecionado)
        self.frNumProcesso.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frNumProcesso.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frNumProcesso.setObjectName("frNumProcesso")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frNumProcesso)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbInfoNumProcesso = QtWidgets.QLabel(self.frNumProcesso)
        self.lbInfoNumProcesso.setObjectName("lbInfoNumProcesso")
        self.horizontalLayout_2.addWidget(self.lbInfoNumProcesso)
        self.lbNumProcesso = QtWidgets.QLabel(self.frNumProcesso)
        self.lbNumProcesso.setObjectName("lbNumProcesso")
        self.horizontalLayout_2.addWidget(self.lbNumProcesso)
        self.gridLayout_2.addWidget(self.frNumProcesso, 0, 1, 1, 1)
        self.frFirulaProcesso = QtWidgets.QFrame(self.frInfoProcSelecionado)
        self.frFirulaProcesso.setMinimumSize(QtCore.QSize(4, 0))
        self.frFirulaProcesso.setMaximumSize(QtCore.QSize(4, 16777215))
        self.frFirulaProcesso.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frFirulaProcesso.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frFirulaProcesso.setObjectName("frFirulaProcesso")
        self.gridLayout_2.addWidget(self.frFirulaProcesso, 0, 0, 2, 1)
        self.verticalLayout_18.addWidget(self.frInfoProcSelecionado)
        self.frInfoDocumentos = QtWidgets.QFrame(self.frInfoGeralProcessos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frInfoDocumentos.sizePolicy().hasHeightForWidth())
        self.frInfoDocumentos.setSizePolicy(sizePolicy)
        self.frInfoDocumentos.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frInfoDocumentos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoDocumentos.setObjectName("frInfoDocumentos")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frInfoDocumentos)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbInfoTituloDocs = QtWidgets.QLabel(self.frInfoDocumentos)
        self.lbInfoTituloDocs.setObjectName("lbInfoTituloDocs")
        self.verticalLayout_4.addWidget(self.lbInfoTituloDocs)
        self.lbInfoDescricao = QtWidgets.QLabel(self.frInfoDocumentos)
        self.lbInfoDescricao.setScaledContents(True)
        self.lbInfoDescricao.setWordWrap(True)
        self.lbInfoDescricao.setObjectName("lbInfoDescricao")
        self.verticalLayout_4.addWidget(self.lbInfoDescricao)
        spacerItem2 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem2)
        self.frame_2 = QtWidgets.QFrame(self.frInfoDocumentos)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(8)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_5.addWidget(self.checkBox, 0, 3, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_5.addWidget(self.checkBox_3, 0, 0, 1, 2)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_5.addWidget(self.checkBox_2, 0, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem3)
        self.frBotoesDocs = QtWidgets.QFrame(self.frInfoDocumentos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frBotoesDocs.sizePolicy().hasHeightForWidth())
        self.frBotoesDocs.setSizePolicy(sizePolicy)
        self.frBotoesDocs.setMaximumSize(QtCore.QSize(260, 50))
        self.frBotoesDocs.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frBotoesDocs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frBotoesDocs.setObjectName("frBotoesDocs")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frBotoesDocs)
        self.horizontalLayout_3.setContentsMargins(8, 0, 8, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frBotoesDocs)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbInfoImprimir = QtWidgets.QLabel(self.frame_6)
        self.lbInfoImprimir.setObjectName("lbInfoImprimir")
        self.horizontalLayout_7.addWidget(self.lbInfoImprimir)
        self.pbImprimir = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbImprimir.sizePolicy().hasHeightForWidth())
        self.pbImprimir.setSizePolicy(sizePolicy)
        self.pbImprimir.setMinimumSize(QtCore.QSize(30, 30))
        self.pbImprimir.setMaximumSize(QtCore.QSize(30, 30))
        self.pbImprimir.setText("")
        self.pbImprimir.setObjectName("pbImprimir")
        self.horizontalLayout_7.addWidget(self.pbImprimir)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.lnSepaDocs = QtWidgets.QFrame(self.frBotoesDocs)
        self.lnSepaDocs.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lnSepaDocs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lnSepaDocs.setFrameShape(QtWidgets.QFrame.VLine)
        self.lnSepaDocs.setObjectName("lnSepaDocs")
        self.horizontalLayout_3.addWidget(self.lnSepaDocs, 0, QtCore.Qt.AlignHCenter)
        self.frame_7 = QtWidgets.QFrame(self.frBotoesDocs)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pbGeraPdf = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbGeraPdf.sizePolicy().hasHeightForWidth())
        self.pbGeraPdf.setSizePolicy(sizePolicy)
        self.pbGeraPdf.setMinimumSize(QtCore.QSize(30, 30))
        self.pbGeraPdf.setMaximumSize(QtCore.QSize(30, 30))
        self.pbGeraPdf.setText("")
        self.pbGeraPdf.setObjectName("pbGeraPdf")
        self.horizontalLayout_8.addWidget(self.pbGeraPdf)
        self.lbInfoGeraPdf = QtWidgets.QLabel(self.frame_7)
        self.lbInfoGeraPdf.setObjectName("lbInfoGeraPdf")
        self.horizontalLayout_8.addWidget(self.lbInfoGeraPdf)
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.verticalLayout_4.addWidget(self.frBotoesDocs)
        self.lbInfoTituloDocs.raise_()
        self.lbInfoDescricao.raise_()
        self.frame_2.raise_()
        self.frBotoesDocs.raise_()
        self.verticalLayout_18.addWidget(self.frInfoDocumentos, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_3.addWidget(self.frInfoGeralProcessos, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frEsquerda, 0, 0, 3, 1)
        self.frDireita = QtWidgets.QFrame(self.frMiolo)
        self.frDireita.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frDireita.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frDireita.setObjectName("frDireita")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frDireita)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frTituloListaProcessos = QtWidgets.QFrame(self.frDireita)
        self.frTituloListaProcessos.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frTituloListaProcessos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frTituloListaProcessos.setObjectName("frTituloListaProcessos")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frTituloListaProcessos)
        self.horizontalLayout_4.setContentsMargins(16, 16, 16, 16)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbTituloListaProcessos = QtWidgets.QLabel(self.frTituloListaProcessos)
        self.lbTituloListaProcessos.setAlignment(QtCore.Qt.AlignCenter)
        self.lbTituloListaProcessos.setObjectName("lbTituloListaProcessos")
        self.horizontalLayout_4.addWidget(self.lbTituloListaProcessos)
        self.verticalLayout_8.addWidget(self.frTituloListaProcessos)
        self.scaListaProcessos = QtWidgets.QScrollArea(self.frDireita)
        self.scaListaProcessos.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scaListaProcessos.setWidgetResizable(True)
        self.scaListaProcessos.setObjectName("scaListaProcessos")
        self.wdgListaProcessos = QtWidgets.QWidget()
        self.wdgListaProcessos.setGeometry(QtCore.QRect(0, 0, 321, 491))
        self.wdgListaProcessos.setObjectName("wdgListaProcessos")
        self.scaListaProcessos.setWidget(self.wdgListaProcessos)
        self.verticalLayout_8.addWidget(self.scaListaProcessos)
        self.gridLayout_6.addWidget(self.frDireita, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frMiolo)
        self.gridLayout.addWidget(self.frPrincipal, 0, 0, 1, 1)

        self.retranslateUi(wdgProcessoPage)
        self.stkInfoCliente.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(wdgProcessoPage)

    def retranslateUi(self, wdgProcessoPage):
        _translate = QtCore.QCoreApplication.translate
        wdgProcessoPage.setWindowTitle(_translate("wdgProcessoPage", "Form"))
        self.lbInfoTitulo.setText(_translate("wdgProcessoPage", "Processos"))
        self.pbBuscarCliente.setText(_translate("wdgProcessoPage", "Buscar cliente"))
        self.lbClienteFoto.setText(_translate("wdgProcessoPage", "TextLabel"))
        self.lbNomeCliente.setText(_translate("wdgProcessoPage", "Nome do cliente"))
        self.lbClienteTelefone.setText(_translate("wdgProcessoPage", "(11) 9 1234 - 5678"))
        self.lbClienteEmail.setText(_translate("wdgProcessoPage", "fulano.deTal@gmail.com"))
        self.lbTpBeneficio.setText(_translate("wdgProcessoPage", "Aposentadoria"))
        self.lbInfoTpBeneficio.setText(_translate("wdgProcessoPage", "Tipo do benefício:"))
        self.lbNatureza.setText(_translate("wdgProcessoPage", "Administrativa"))
        self.lbInfoTpProcesso.setText(_translate("wdgProcessoPage", "Tipo do processo:"))
        self.lbInfoNatureza.setText(_translate("wdgProcessoPage", "Natureza:"))
        self.lbTpProcesso.setText(_translate("wdgProcessoPage", "Concessão"))
        self.lbInfoNumProcesso.setText(_translate("wdgProcessoPage", "Processo: "))
        self.lbNumProcesso.setText(_translate("wdgProcessoPage", "NumProcesso"))
        self.lbInfoTituloDocs.setText(_translate("wdgProcessoPage", "Documentos"))
        self.lbInfoDescricao.setText(_translate("wdgProcessoPage", "Selecione os documentos que deseja imprimir ou gerar PDF."))
        self.checkBox.setText(_translate("wdgProcessoPage", "CheckBox"))
        self.checkBox_3.setText(_translate("wdgProcessoPage", "CheckBox"))
        self.checkBox_2.setText(_translate("wdgProcessoPage", "CheckBox"))
        self.lbInfoImprimir.setText(_translate("wdgProcessoPage", "Imprimir tudo"))
        self.lbInfoGeraPdf.setText(_translate("wdgProcessoPage", "Gerar PDF\'s"))
        self.lbTituloListaProcessos.setText(_translate("wdgProcessoPage", "Lista de processos"))
import Resources.processoPage


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgProcessoPage = QtWidgets.QWidget()
    ui = Ui_wdgProcessoPage()
    ui.setupUi(wdgProcessoPage)
    wdgProcessoPage.show()
    sys.exit(app.exec_())
