# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design/UI/processoCard.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgProcessoCard(object):
    def setupUi(self, wdgProcessoCard):
        wdgProcessoCard.setObjectName("wdgProcessoCard")
        wdgProcessoCard.resize(333, 109)
        wdgProcessoCard.setStyleSheet("/* --------- Label --------- */\n"
"\n"
"#lbInfoNatureza, #lbInfoTpBeneficio,\n"
"#lbInfoTpProcesso {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: #3A405A;\n"
"    font-weight: 750;\n"
"}\n"
"\n"
"#lbNatureza, #lbTpBeneficio,\n"
"#lbTpProcesso, #lbInfoDescricao,\n"
"#lbNumProcesso {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: #3A405A;\n"
"    font-weight: 200;\n"
"}\n"
"\n"
"#lbInfoNumProcesso {\n"
"    font: 16pt \"Avenir LT Std\";\n"
"    color: #3F4E8C;\n"
"    font-weight: 750;\n"
"}\n"
"\n"
"/* --------- Frame --------- */\n"
"\n"
"#frInfoProcesso {\n"
"    background-color: #F9F9F9;\n"
"    border: 0px solid none;\n"
"    border-radius: 8px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(wdgProcessoCard)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frInfoProcesso = QtWidgets.QFrame(wdgProcessoCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frInfoProcesso.sizePolicy().hasHeightForWidth())
        self.frInfoProcesso.setSizePolicy(sizePolicy)
        self.frInfoProcesso.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frInfoProcesso.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoProcesso.setObjectName("frInfoProcesso")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frInfoProcesso)
        self.gridLayout_3.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_3.setHorizontalSpacing(8)
        self.gridLayout_3.setVerticalSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frNumProcesso = QtWidgets.QFrame(self.frInfoProcesso)
        self.frNumProcesso.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frNumProcesso.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frNumProcesso.setObjectName("frNumProcesso")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frNumProcesso)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbInfoNumProcesso = QtWidgets.QLabel(self.frNumProcesso)
        self.lbInfoNumProcesso.setObjectName("lbInfoNumProcesso")
        self.horizontalLayout_3.addWidget(self.lbInfoNumProcesso)
        self.lbNumProcesso = QtWidgets.QLabel(self.frNumProcesso)
        self.lbNumProcesso.setObjectName("lbNumProcesso")
        self.horizontalLayout_3.addWidget(self.lbNumProcesso)
        self.gridLayout_3.addWidget(self.frNumProcesso, 0, 0, 1, 1)
        self.frInfoProc = QtWidgets.QFrame(self.frInfoProcesso)
        self.frInfoProc.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frInfoProc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoProc.setObjectName("frInfoProc")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frInfoProc)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(0)
        self.gridLayout_5.setVerticalSpacing(8)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lbInfoNatureza = QtWidgets.QLabel(self.frInfoProc)
        self.lbInfoNatureza.setObjectName("lbInfoNatureza")
        self.gridLayout_5.addWidget(self.lbInfoNatureza, 0, 0, 1, 1)
        self.lbNatureza = QtWidgets.QLabel(self.frInfoProc)
        self.lbNatureza.setObjectName("lbNatureza")
        self.gridLayout_5.addWidget(self.lbNatureza, 0, 1, 1, 1)
        self.lbInfoTpBeneficio = QtWidgets.QLabel(self.frInfoProc)
        self.lbInfoTpBeneficio.setObjectName("lbInfoTpBeneficio")
        self.gridLayout_5.addWidget(self.lbInfoTpBeneficio, 1, 0, 1, 1)
        self.lbTpBeneficio = QtWidgets.QLabel(self.frInfoProc)
        self.lbTpBeneficio.setObjectName("lbTpBeneficio")
        self.gridLayout_5.addWidget(self.lbTpBeneficio, 1, 1, 1, 1)
        self.lbInfoTpProcesso = QtWidgets.QLabel(self.frInfoProc)
        self.lbInfoTpProcesso.setObjectName("lbInfoTpProcesso")
        self.gridLayout_5.addWidget(self.lbInfoTpProcesso, 2, 0, 1, 1)
        self.lbTpProcesso = QtWidgets.QLabel(self.frInfoProc)
        self.lbTpProcesso.setObjectName("lbTpProcesso")
        self.gridLayout_5.addWidget(self.lbTpProcesso, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frInfoProc, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frInfoProcesso)

        self.retranslateUi(wdgProcessoCard)
        QtCore.QMetaObject.connectSlotsByName(wdgProcessoCard)

    def retranslateUi(self, wdgProcessoCard):
        _translate = QtCore.QCoreApplication.translate
        wdgProcessoCard.setWindowTitle(_translate("wdgProcessoCard", "Form"))
        self.lbInfoNumProcesso.setText(_translate("wdgProcessoCard", "Processo: "))
        self.lbNumProcesso.setText(_translate("wdgProcessoCard", "NumProcesso"))
        self.lbInfoNatureza.setText(_translate("wdgProcessoCard", "Natureza:"))
        self.lbNatureza.setText(_translate("wdgProcessoCard", "Administrativa"))
        self.lbInfoTpBeneficio.setText(_translate("wdgProcessoCard", "Tipo do benefício:"))
        self.lbTpBeneficio.setText(_translate("wdgProcessoCard", "Aposentadoria"))
        self.lbInfoTpProcesso.setText(_translate("wdgProcessoCard", "Tipo do processo:"))
        self.lbTpProcesso.setText(_translate("wdgProcessoCard", "Concessão"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgProcessoCard = QtWidgets.QWidget()
    ui = Ui_wdgProcessoCard()
    ui.setupUi(wdgProcessoCard)
    wdgProcessoCard.show()
    sys.exit(app.exec_())
