# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabCalculos.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgTabCalculos(object):
    def setupUi(self, wdgTabCalculos):
        wdgTabCalculos.setObjectName("wdgTabCalculos")
        wdgTabCalculos.resize(1197, 764)
        wdgTabCalculos.setMinimumSize(QtCore.QSize(945, 611))
        wdgTabCalculos.setStyleSheet("#tabContribuicoes,\n"
"#tabMain, \n"
"#tabCalculos,\n"
"#tabBeneficios,\n"
"#tabResumo {\n"
"    border-radius: 8px;\n"
"    background-color: white;\n"
"    padding: 4px;\n"
"    \n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"#tabMain::pane {\n"
"    background-color: transparent;\n"
"    border-radius: 8px;\n"
"/*    border-top: 4px solid rgb(52, 73, 94);\n"
"    border-bottom: 4px solid rgb(52, 73, 94);\n"
"    border-right: 4px solid rgb(52, 73, 94);\n"
"    border-left: 4px solid rgba(66, 147, 215, 255);*/\n"
"\n"
"    border: 4px solid transparent;\n"
"}\n"
"\n"
"#tabMain::tab-bar {\n"
"    /*left: 250px;*/\n"
"    alignment: center;\n"
"    width: 60ex;\n"
"}\n"
"\n"
"QTabBar::tab{\n"
"    background: grey;\n"
"/*    color: rgb(52, 73, 94);*/\n"
"    color: white;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    border: 2px solid white;\n"
"    padding: 4px;\n"
"    \n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: rgb(52, 73, 94);\n"
"    font-weight: bold;\n"
"    color: white;\n"
"/*    min-width: 3ex;*/\n"
"    margin-left: 4px;\n"
"    margin-right: 4px;\n"
"\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: rgb(92, 113, 134);\n"
"    color: white;\n"
"/*    min-width: 16ex;*/\n"
"    margin-left: 1px;\n"
"    margin-right: 1px;\n"
"    margin-top: 2px;\n"
"\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(wdgTabCalculos)
        self.horizontalLayout.setContentsMargins(0, 4, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabMain = QtWidgets.QTabWidget(wdgTabCalculos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabMain.sizePolicy().hasHeightForWidth())
        self.tabMain.setSizePolicy(sizePolicy)
        self.tabMain.setMinimumSize(QtCore.QSize(0, 500))
        self.tabMain.setStyleSheet("")
        self.tabMain.setIconSize(QtCore.QSize(36, 16))
        self.tabMain.setObjectName("tabMain")
        self.tabResumo = QtWidgets.QWidget()
        self.tabResumo.setStyleSheet("/*-------------------------------- Labels -----------------------------------------*/\n"
"#lbTituloClientesResumo {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 24px;\n"
"}\n"
"\n"
"#lbInfoClientesResumo {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;    \n"
"}\n"
"\n"
"#lbTituloFiltroResumo {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"#lbBuscaNomeResumo, #lbBuscaEmailResumo, \n"
"#lbBuscaTelefoneResumo, #lbBuscaTpProcessoResumo,\n"
"#lbBuscaRgcpfResumo {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#lbInfoCabecalhoResumo, #lbInfoDibDerResumo, \n"
"#lbInfoNomeResumo, #lbInfoDocumentoResumo {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"#lbDibDerResumo, \n"
"#lbNomeResumo, #lbDocumentoResumo {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 14px;\n"
"    background-color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/*-------------------------------- Frames -----------------------------------------*/\n"
"#frInfoCabecalhoResumo {\n"
"    border-radius: 4px;\n"
"    border: 1px solid rgb(85, 87, 83);\n"
"\n"
"    background-color: white;\n"
"}\n"
"\n"
"/*-------------------------------- Push Buttons --------------------------------*/\n"
"\n"
"#pbBuscarClienteResumo {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 14px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    background-color: rgb(52, 73, 94);\n"
"}\n"
"\n"
"#pbBuscarClienteResumo:hover {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 14px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    border: 1px solid;\n"
"    background-color: rgb(72, 93, 114);\n"
"}\n"
"\n"
"#pbInserirResumo, #pbEditarResumo, #pbExcluirResumo {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    background-color: rgb(52, 73, 94);\n"
"}\n"
"\n"
"#pbInserirResumo:hover, #pbEditarResumo:hover, \n"
"#pbExcluirResumo:hover {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    border: 1px solid;\n"
"    background-color: rgb(72, 93, 114);\n"
"}\n"
"\n"
"/*-------------------------------- Scroll Area --------------------------------*/\n"
"#scaResumos {\n"
"    background-color: white;\n"
"}\n"
"\n"
"/*-------------------------------- Group Box -----------------------------------------*/\n"
"QGroupBox {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 16px;\n"
"    border: 1px solid transparent;\n"
"\n"
"    background-color: white;\n"
"}\n"
"\n"
"#bpInfoPessoaisResumo::title, #gbInfoBancarias::title,\n"
"#gbInfoProfissionais::title, #gbInfoResidenciais::title {\n"
"    subcontrol-position: top left;\n"
"    background-color: #3A405A;\n"
"    border-top-left-radius: 8px;\n"
"    border-top-right-radius: 8px;\n"
"    color: white;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"#bpInfoPessoaisResumo, #gbInfoBancarias,\n"
"#gbInfoProfissionais, #gbInfoResidenciais{\n"
"    border: 1px dashed grey;\n"
"}\n"
"")
        self.tabResumo.setObjectName("tabResumo")
        self.gridLayout = QtWidgets.QGridLayout(self.tabResumo)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_5 = QtWidgets.QFrame(self.tabResumo)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(32)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbTituloClientesResumo = QtWidgets.QLabel(self.frame_4)
        self.lbTituloClientesResumo.setObjectName("lbTituloClientesResumo")
        self.verticalLayout_3.addWidget(self.lbTituloClientesResumo)
        self.lbInfoClientesResumo = QtWidgets.QLabel(self.frame_4)
        self.lbInfoClientesResumo.setObjectName("lbInfoClientesResumo")
        self.verticalLayout_3.addWidget(self.lbInfoClientesResumo)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.bpInfoPessoaisResumo = QtWidgets.QGroupBox(self.frame_5)
        self.bpInfoPessoaisResumo.setObjectName("bpInfoPessoaisResumo")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.bpInfoPessoaisResumo)
        self.verticalLayout_4.setContentsMargins(8, 26, 34, 0)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.bpInfoPessoaisResumo)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbInfoNomeResumo = QtWidgets.QLabel(self.frame_6)
        self.lbInfoNomeResumo.setObjectName("lbInfoNomeResumo")
        self.horizontalLayout_4.addWidget(self.lbInfoNomeResumo, 0, QtCore.Qt.AlignLeft)
        self.lbNomeResumo = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbNomeResumo.sizePolicy().hasHeightForWidth())
        self.lbNomeResumo.setSizePolicy(sizePolicy)
        self.lbNomeResumo.setText("")
        self.lbNomeResumo.setObjectName("lbNomeResumo")
        self.horizontalLayout_4.addWidget(self.lbNomeResumo, 0, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.bpInfoPessoaisResumo)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbInfoDocumentoResumo = QtWidgets.QLabel(self.frame_7)
        self.lbInfoDocumentoResumo.setObjectName("lbInfoDocumentoResumo")
        self.horizontalLayout_5.addWidget(self.lbInfoDocumentoResumo, 0, QtCore.Qt.AlignLeft)
        self.lbDocumentoResumo = QtWidgets.QLabel(self.frame_7)
        self.lbDocumentoResumo.setText("")
        self.lbDocumentoResumo.setObjectName("lbDocumentoResumo")
        self.horizontalLayout_5.addWidget(self.lbDocumentoResumo, 0, QtCore.Qt.AlignLeft)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.horizontalLayout_3.addWidget(self.bpInfoPessoaisResumo)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addWidget(self.frame_5, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.tabResumo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 560))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(16)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(800, 400))
        self.scrollArea.setStyleSheet("/*#scrollArea, #scaResumos{\n"
"    background-color: grey;\n"
"}*/")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scaResumos = QtWidgets.QWidget()
        self.scaResumos.setGeometry(QtCore.QRect(0, 0, 1065, 618))
        self.scaResumos.setObjectName("scaResumos")
        self.scrollArea.setWidget(self.scaResumos)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setMinimumSize(QtCore.QSize(80, 0))
        self.frame.setMaximumSize(QtCore.QSize(90, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 16, 0, 0)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbBuscarClienteResumo = QtWidgets.QPushButton(self.frame)
        self.pbBuscarClienteResumo.setMinimumSize(QtCore.QSize(80, 32))
        self.pbBuscarClienteResumo.setMaximumSize(QtCore.QSize(90, 32))
        self.pbBuscarClienteResumo.setObjectName("pbBuscarClienteResumo")
        self.verticalLayout.addWidget(self.pbBuscarClienteResumo, 0, QtCore.Qt.AlignTop)
        self.pbInserirResumo = QtWidgets.QPushButton(self.frame)
        self.pbInserirResumo.setMinimumSize(QtCore.QSize(80, 32))
        self.pbInserirResumo.setMaximumSize(QtCore.QSize(90, 32))
        self.pbInserirResumo.setObjectName("pbInserirResumo")
        self.verticalLayout.addWidget(self.pbInserirResumo, 0, QtCore.Qt.AlignTop)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2.addWidget(self.frame)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 1)
        self.tabMain.addTab(self.tabResumo, "")
        self.tabContribuicoes = QtWidgets.QWidget()
        self.tabContribuicoes.setStyleSheet("/*-------------------------------- Labels -----------------------------------------*/\n"
"#lbTituloClientes {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 24px;\n"
"}\n"
"\n"
"#lbInfoClientes {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;    \n"
"}\n"
"\n"
"#lbTituloFiltro {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"#lbBuscaNome, #lbBuscaEmail, \n"
"#lbBuscaTelefone, #lbBuscaTpProcesso,\n"
"#lbBuscaRgcpf {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#lbInfoCabecalho, #lbInfoDibDer, \n"
"#lbInfoNome, #lbInfoDocumento {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"#lbDibDer, \n"
"#lbNome, #lbDocumento {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 14px;\n"
"    background-color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/*-------------------------------- Frames -----------------------------------------*/\n"
"#frInfoCabecalho{\n"
"    border-radius: 4px;\n"
"    border: 1px solid rgb(85, 87, 83);\n"
"\n"
"    background-color: white;\n"
"}\n"
"\n"
"/*-------------------------------- Tables -----------------------------------------*/\n"
"#tblCalculos {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"#tblClientes::item{\n"
"    margin: 4px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(52, 73, 94);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    min-height: 45px;\n"
"}\n"
"\n"
"QHeaderView::down-arrow {\n"
"    icon-color: white;\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    icon-color: white;\n"
"}\n"
"\n"
"/*-------------------------------- Push Buttons --------------------------------*/\n"
"\n"
"#pbBuscarCliente {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 14px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    background-color: rgb(52, 73, 94);\n"
"}\n"
"\n"
"#pbBuscarCliente:hover {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 14px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    border: 1px solid;\n"
"    background-color: rgb(72, 93, 114);\n"
"}\n"
"\n"
"#pbInserir, #pbEditar, #pbExcluir {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    background-color: rgb(52, 73, 94);\n"
"}\n"
"\n"
"#pbInserir:hover, #pbEditar:hover, \n"
"#pbExcluir:hover {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    border: 1px solid;\n"
"    background-color: rgb(72, 93, 114);\n"
"}")
        self.tabContribuicoes.setObjectName("tabContribuicoes")
        self.lbTituloClientes = QtWidgets.QLabel(self.tabContribuicoes)
        self.lbTituloClientes.setGeometry(QtCore.QRect(10, 10, 361, 31))
        self.lbTituloClientes.setObjectName("lbTituloClientes")
        self.lbInfoClientes = QtWidgets.QLabel(self.tabContribuicoes)
        self.lbInfoClientes.setGeometry(QtCore.QRect(10, 40, 371, 31))
        self.lbInfoClientes.setObjectName("lbInfoClientes")
        self.tblCalculos = QtWidgets.QTableWidget(self.tabContribuicoes)
        self.tblCalculos.setGeometry(QtCore.QRect(20, 100, 991, 461))
        self.tblCalculos.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tblCalculos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblCalculos.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblCalculos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblCalculos.setShowGrid(False)
        self.tblCalculos.setWordWrap(True)
        self.tblCalculos.setObjectName("tblCalculos")
        self.tblCalculos.setColumnCount(7)
        self.tblCalculos.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tblCalculos.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCalculos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("TeX Gyre Adventor")
        font.setPointSize(12)
        item.setFont(font)
        self.tblCalculos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("TeX Gyre Adventor")
        font.setPointSize(12)
        item.setFont(font)
        self.tblCalculos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("TeX Gyre Adventor")
        font.setPointSize(12)
        item.setFont(font)
        self.tblCalculos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("TeX Gyre Adventor")
        font.setPointSize(12)
        item.setFont(font)
        self.tblCalculos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("TeX Gyre Adventor")
        font.setPointSize(12)
        item.setFont(font)
        self.tblCalculos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("TeX Gyre Adventor")
        font.setPointSize(12)
        item.setFont(font)
        self.tblCalculos.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tblCalculos.setItem(0, 6, item)
        self.tblCalculos.horizontalHeader().setCascadingSectionResizes(True)
        self.tblCalculos.horizontalHeader().setSortIndicatorShown(True)
        self.tblCalculos.horizontalHeader().setStretchLastSection(True)
        self.tblCalculos.verticalHeader().setVisible(False)
        self.pbBuscarCliente = QtWidgets.QPushButton(self.tabContribuicoes)
        self.pbBuscarCliente.setGeometry(QtCore.QRect(1030, 150, 101, 41))
        self.pbBuscarCliente.setObjectName("pbBuscarCliente")
        self.frInfoCabecalho = QtWidgets.QFrame(self.tabContribuicoes)
        self.frInfoCabecalho.setGeometry(QtCore.QRect(420, 10, 401, 81))
        self.frInfoCabecalho.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frInfoCabecalho.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoCabecalho.setObjectName("frInfoCabecalho")
        self.lbInfoNome = QtWidgets.QLabel(self.frInfoCabecalho)
        self.lbInfoNome.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.lbInfoNome.setObjectName("lbInfoNome")
        self.lbInfoDocumento = QtWidgets.QLabel(self.frInfoCabecalho)
        self.lbInfoDocumento.setGeometry(QtCore.QRect(10, 50, 81, 21))
        self.lbInfoDocumento.setObjectName("lbInfoDocumento")
        self.lbNome = QtWidgets.QLabel(self.frInfoCabecalho)
        self.lbNome.setGeometry(QtCore.QRect(100, 10, 221, 21))
        self.lbNome.setText("")
        self.lbNome.setObjectName("lbNome")
        self.lbDocumento = QtWidgets.QLabel(self.frInfoCabecalho)
        self.lbDocumento.setGeometry(QtCore.QRect(100, 50, 191, 21))
        self.lbDocumento.setText("")
        self.lbDocumento.setObjectName("lbDocumento")
        self.lbInfoCabecalho = QtWidgets.QLabel(self.tabContribuicoes)
        self.lbInfoCabecalho.setGeometry(QtCore.QRect(440, 0, 141, 17))
        self.lbInfoCabecalho.setObjectName("lbInfoCabecalho")
        self.pbInserir = QtWidgets.QPushButton(self.tabContribuicoes)
        self.pbInserir.setGeometry(QtCore.QRect(1030, 220, 101, 25))
        self.pbInserir.setObjectName("pbInserir")
        self.pbExcluir = QtWidgets.QPushButton(self.tabContribuicoes)
        self.pbExcluir.setGeometry(QtCore.QRect(1030, 270, 101, 25))
        self.pbExcluir.setObjectName("pbExcluir")
        self.pbEditar = QtWidgets.QPushButton(self.tabContribuicoes)
        self.pbEditar.setGeometry(QtCore.QRect(1030, 320, 101, 25))
        self.pbEditar.setObjectName("pbEditar")
        self.tabMain.addTab(self.tabContribuicoes, "")
        self.tabBeneficios = QtWidgets.QWidget()
        self.tabBeneficios.setStyleSheet("/*-------------------------------- Labels -----------------------------------------*/\n"
"#lbTituloClientesBen {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 24px;\n"
"}\n"
"\n"
"#lbInfoClientesBen {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;    \n"
"}\n"
"\n"
"#lbTituloFiltroBen {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"#lbBuscaNomeBen, #lbBuscaEmailBen, \n"
"#lbBuscaTelefoneBen, #lbBuscaTpProcessoBen,\n"
"#lbBuscaRgcpfBen {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#lbInfoCabecalhoBen, #lbInfoDibDerBen, \n"
"#lbInfoNomeBen, #lbInfoDocumentoBen {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"#lbDibDerBen, \n"
"#lbNomeBen, #lbDocumentoBen {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 14px;\n"
"    background-color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/*-------------------------------- Frames -----------------------------------------*/\n"
"#frInfoCabecalhoBen {\n"
"    border-radius: 4px;\n"
"    border: 1px solid rgb(85, 87, 83);\n"
"\n"
"    background-color: white;\n"
"}\n"
"\n"
"/*-------------------------------- Tables -----------------------------------------*/\n"
"#tblBeneficios {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"#tblClientesBen::item{\n"
"    margin: 4px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(52, 73, 94);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    min-height: 45px;\n"
"}\n"
"\n"
"QHeaderView::down-arrow {\n"
"    icon-color: white;\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    icon-color: white;\n"
"}\n"
"\n"
"/*-------------------------------- Push Buttons --------------------------------*/\n"
"#pbArrowNomeBen, \n"
"#pbArrowEmailBen, \n"
"#pbArrowTelefoneBen,\n"
"#pbArrowTpProcessoBen,\n"
"#pbArrowRgcpfBen {\n"
"    background-image: url(:/arrowDown/arrowDown.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"#pbBuscarClienteBen {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 14px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    background-color: rgb(52, 73, 94);\n"
"}\n"
"\n"
"#pbBuscarClienteBen:hover {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 14px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    border: 1px solid;\n"
"    background-color: rgb(72, 93, 114);\n"
"}\n"
"\n"
"#pbInserirBen, #pbEditarBen, #pbExcluirBen {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    background-color: rgb(52, 73, 94);\n"
"}\n"
"\n"
"#pbInserirBen:hover, #pbEditarBen:hover, \n"
"#pbExcluirBen:hover {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"    color: white;\n"
"\n"
"    border-radius: 4px;\n"
"    border: 1px solid;\n"
"    background-color: rgb(72, 93, 114);\n"
"}")
        self.tabBeneficios.setObjectName("tabBeneficios")
        self.pbExcluirBen = QtWidgets.QPushButton(self.tabBeneficios)
        self.pbExcluirBen.setGeometry(QtCore.QRect(1030, 270, 101, 25))
        self.pbExcluirBen.setObjectName("pbExcluirBen")
        self.lbInfoClientesBen = QtWidgets.QLabel(self.tabBeneficios)
        self.lbInfoClientesBen.setGeometry(QtCore.QRect(10, 40, 371, 31))
        self.lbInfoClientesBen.setObjectName("lbInfoClientesBen")
        self.pbBuscarClienteBen = QtWidgets.QPushButton(self.tabBeneficios)
        self.pbBuscarClienteBen.setGeometry(QtCore.QRect(1030, 150, 101, 41))
        self.pbBuscarClienteBen.setObjectName("pbBuscarClienteBen")
        self.pbEditarBen = QtWidgets.QPushButton(self.tabBeneficios)
        self.pbEditarBen.setGeometry(QtCore.QRect(1030, 320, 101, 25))
        self.pbEditarBen.setObjectName("pbEditarBen")
        self.tblBeneficios = QtWidgets.QTableWidget(self.tabBeneficios)
        self.tblBeneficios.setGeometry(QtCore.QRect(20, 100, 991, 461))
        self.tblBeneficios.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tblBeneficios.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblBeneficios.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblBeneficios.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblBeneficios.setShowGrid(False)
        self.tblBeneficios.setWordWrap(True)
        self.tblBeneficios.setObjectName("tblBeneficios")
        self.tblBeneficios.setColumnCount(5)
        self.tblBeneficios.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblBeneficios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("TeX Gyre Adventor")
        font.setPointSize(12)
        item.setFont(font)
        self.tblBeneficios.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("TeX Gyre Adventor")
        font.setPointSize(12)
        item.setFont(font)
        self.tblBeneficios.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("TeX Gyre Adventor")
        font.setPointSize(12)
        item.setFont(font)
        self.tblBeneficios.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("TeX Gyre Adventor")
        font.setPointSize(12)
        item.setFont(font)
        self.tblBeneficios.setHorizontalHeaderItem(4, item)
        self.tblBeneficios.horizontalHeader().setCascadingSectionResizes(True)
        self.tblBeneficios.horizontalHeader().setSortIndicatorShown(True)
        self.tblBeneficios.horizontalHeader().setStretchLastSection(True)
        self.tblBeneficios.verticalHeader().setVisible(False)
        self.frInfoCabecalhoBen = QtWidgets.QFrame(self.tabBeneficios)
        self.frInfoCabecalhoBen.setGeometry(QtCore.QRect(420, 10, 401, 81))
        self.frInfoCabecalhoBen.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frInfoCabecalhoBen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frInfoCabecalhoBen.setObjectName("frInfoCabecalhoBen")
        self.lbInfoNomeBen = QtWidgets.QLabel(self.frInfoCabecalhoBen)
        self.lbInfoNomeBen.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.lbInfoNomeBen.setObjectName("lbInfoNomeBen")
        self.lbInfoDocumentoBen = QtWidgets.QLabel(self.frInfoCabecalhoBen)
        self.lbInfoDocumentoBen.setGeometry(QtCore.QRect(10, 50, 81, 21))
        self.lbInfoDocumentoBen.setObjectName("lbInfoDocumentoBen")
        self.lbNomeBen = QtWidgets.QLabel(self.frInfoCabecalhoBen)
        self.lbNomeBen.setGeometry(QtCore.QRect(100, 10, 221, 21))
        self.lbNomeBen.setText("")
        self.lbNomeBen.setObjectName("lbNomeBen")
        self.lbDocumentoBen = QtWidgets.QLabel(self.frInfoCabecalhoBen)
        self.lbDocumentoBen.setGeometry(QtCore.QRect(100, 50, 191, 21))
        self.lbDocumentoBen.setText("")
        self.lbDocumentoBen.setObjectName("lbDocumentoBen")
        self.pbInserirBen = QtWidgets.QPushButton(self.tabBeneficios)
        self.pbInserirBen.setGeometry(QtCore.QRect(1030, 220, 101, 25))
        self.pbInserirBen.setObjectName("pbInserirBen")
        self.lbInfoCabecalhoBen = QtWidgets.QLabel(self.tabBeneficios)
        self.lbInfoCabecalhoBen.setGeometry(QtCore.QRect(440, 0, 141, 17))
        self.lbInfoCabecalhoBen.setObjectName("lbInfoCabecalhoBen")
        self.lbTituloClientesBen = QtWidgets.QLabel(self.tabBeneficios)
        self.lbTituloClientesBen.setGeometry(QtCore.QRect(10, 10, 361, 31))
        self.lbTituloClientesBen.setObjectName("lbTituloClientesBen")
        self.tabMain.addTab(self.tabBeneficios, "")
        self.horizontalLayout.addWidget(self.tabMain)

        self.retranslateUi(wdgTabCalculos)
        self.tabMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(wdgTabCalculos)

    def retranslateUi(self, wdgTabCalculos):
        _translate = QtCore.QCoreApplication.translate
        wdgTabCalculos.setWindowTitle(_translate("wdgTabCalculos", "Form"))
        self.lbTituloClientesResumo.setText(_translate("wdgTabCalculos", "Resumo do CNIS"))
        self.lbInfoClientesResumo.setText(_translate("wdgTabCalculos", "Resumo das contribuições e benefícios"))
        self.bpInfoPessoaisResumo.setTitle(_translate("wdgTabCalculos", "Informações pessoais"))
        self.lbInfoNomeResumo.setText(_translate("wdgTabCalculos", "Nome cliente:"))
        self.lbInfoDocumentoResumo.setText(_translate("wdgTabCalculos", "Documento:"))
        self.pbBuscarClienteResumo.setText(_translate("wdgTabCalculos", "Buscar \n"
"cliente"))
        self.pbInserirResumo.setText(_translate("wdgTabCalculos", "Inserir"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabResumo), _translate("wdgTabCalculos", "Resumo"))
        self.lbTituloClientes.setText(_translate("wdgTabCalculos", "Tabela de Remunerações"))
        self.lbInfoClientes.setText(_translate("wdgTabCalculos", "Pesquise por toda a sua base de clientes"))
        item = self.tblCalculos.verticalHeaderItem(0)
        item.setText(_translate("wdgTabCalculos", "New Row"))
        item = self.tblCalculos.horizontalHeaderItem(0)
        item.setText(_translate("wdgTabCalculos", "infoId"))
        item = self.tblCalculos.horizontalHeaderItem(1)
        item.setText(_translate("wdgTabCalculos", "Nº"))
        item = self.tblCalculos.horizontalHeaderItem(2)
        item.setText(_translate("wdgTabCalculos", "Data"))
        item = self.tblCalculos.horizontalHeaderItem(3)
        item.setText(_translate("wdgTabCalculos", "Salário de \n"
"Contribuição"))
        item = self.tblCalculos.horizontalHeaderItem(4)
        item.setText(_translate("wdgTabCalculos", "Tetos \n"
"Previdenciários"))
        item = self.tblCalculos.horizontalHeaderItem(5)
        item.setText(_translate("wdgTabCalculos", "Natureza"))
        item = self.tblCalculos.horizontalHeaderItem(6)
        item.setText(_translate("wdgTabCalculos", "Indicadores"))
        __sortingEnabled = self.tblCalculos.isSortingEnabled()
        self.tblCalculos.setSortingEnabled(False)
        self.tblCalculos.setSortingEnabled(__sortingEnabled)
        self.pbBuscarCliente.setText(_translate("wdgTabCalculos", "Buscar \n"
"cliente"))
        self.lbInfoNome.setText(_translate("wdgTabCalculos", "Nome cliente:"))
        self.lbInfoDocumento.setText(_translate("wdgTabCalculos", "Documento:"))
        self.lbInfoCabecalho.setText(_translate("wdgTabCalculos", "  Informações pessoais"))
        self.pbInserir.setText(_translate("wdgTabCalculos", "Inserir"))
        self.pbExcluir.setText(_translate("wdgTabCalculos", "Excluir"))
        self.pbEditar.setText(_translate("wdgTabCalculos", "Editar"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabContribuicoes), _translate("wdgTabCalculos", "Contribuições"))
        self.pbExcluirBen.setText(_translate("wdgTabCalculos", "Excluir"))
        self.lbInfoClientesBen.setText(_translate("wdgTabCalculos", "Pesquise por toda a sua base de clientes"))
        self.pbBuscarClienteBen.setText(_translate("wdgTabCalculos", "Buscar \n"
"cliente"))
        self.pbEditarBen.setText(_translate("wdgTabCalculos", "Editar"))
        item = self.tblBeneficios.horizontalHeaderItem(0)
        item.setText(_translate("wdgTabCalculos", "infoId"))
        item = self.tblBeneficios.horizontalHeaderItem(1)
        item.setText(_translate("wdgTabCalculos", "Nº"))
        item = self.tblBeneficios.horizontalHeaderItem(2)
        item.setText(_translate("wdgTabCalculos", "Número do\n"
"benefício"))
        item = self.tblBeneficios.horizontalHeaderItem(3)
        item.setText(_translate("wdgTabCalculos", "Competência"))
        item = self.tblBeneficios.horizontalHeaderItem(4)
        item.setText(_translate("wdgTabCalculos", "Valor do benefício"))
        self.lbInfoNomeBen.setText(_translate("wdgTabCalculos", "Nome cliente:"))
        self.lbInfoDocumentoBen.setText(_translate("wdgTabCalculos", "Documento:"))
        self.pbInserirBen.setText(_translate("wdgTabCalculos", "Inserir"))
        self.lbInfoCabecalhoBen.setText(_translate("wdgTabCalculos", "  Informações pessoais"))
        self.lbTituloClientesBen.setText(_translate("wdgTabCalculos", "Tabela de Benefícios"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabBeneficios), _translate("wdgTabCalculos", "Benefícios"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgTabCalculos = QtWidgets.QWidget()
    ui = Ui_wdgTabCalculos()
    ui.setupUi(wdgTabCalculos)
    wdgTabCalculos.show()
    sys.exit(app.exec_())
