# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design/UI/wdgCardAposentadoria.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgCardAposentadoria(object):
    def setupUi(self, wdgCardAposentadoria):
        wdgCardAposentadoria.setObjectName("wdgCardAposentadoria")
        wdgCardAposentadoria.resize(253, 264)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wdgCardAposentadoria.sizePolicy().hasHeightForWidth())
        wdgCardAposentadoria.setSizePolicy(sizePolicy)
        wdgCardAposentadoria.setMinimumSize(QtCore.QSize(253, 264))
        wdgCardAposentadoria.setMaximumSize(QtCore.QSize(253, 264))
        wdgCardAposentadoria.setStyleSheet("/*#wdgCardAposentadoria {\n"
"    background-color: black;\n"
"}*/\n"
"\n"
"/*------------------------------------- Label -------------------------------------*/\n"
"#lbTipoApos, #lbDib {\n"
"    font: 14pt \"Avenir LT Std\";\n"
"    color: #3A405A;\n"
"\n"
"    margin-left: 0px;\n"
"    margin-right: 0px;\n"
"    margin-top: 16px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"#lbIdade {\n"
"    font: 20pt \"Avenir LT Std\";\n"
"    color: #3F4E8C;\n"
"}\n"
"\n"
"#lbQtdContrib {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: #3A405A;\n"
"\n"
"    font-weight: 750;\n"
"}\n"
"\n"
"#lbValorBeneficio {\n"
"    font: 18pt \"Avenir LT Std\";\n"
"    color: white;\n"
"    \n"
"    font-weight: 750;\n"
"}\n"
"\n"
"/*------------------------------------- Frame -------------------------------------*/\n"
"#frMain {\n"
"    background-color: white;\n"
"    border-radius: 16px;\n"
"\n"
"    border: 2px solid #3F4E8C;\n"
"}\n"
"\n"
"#frIconeCentral {\n"
"    border-width: 0px;\n"
"    border-color: grey;\n"
"    border-style: solid;\n"
"\n"
"    border-radius: 60px;\n"
"    background-color: rgb(250, 156, 62);\n"
"}\n"
"\n"
"#frSeparador1 {\n"
"    background-color: lightgrey;\n"
"}\n"
"\n"
"#frBottom {\n"
"    background-color: #3F4E8C;\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 13px;\n"
"    border-bottom-left-radius: 13px;\n"
"}\n"
"\n"
"/*------------------------------------- Progress Bar  -------------------------------------*/\n"
"#pbarPrincipal {\n"
"    border: 2px solid grey;\n"
"    border-radius: 12px;\n"
"\n"
"    margin-left: 16px;\n"
"    margin-right: 16px;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"#pbarPrincipal::chunk {\n"
"    background-color: #3F64FF;\n"
"    \n"
"    border-bottom-left-radius: 10px; \n"
"    border-top-left-radius: 10px;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(wdgCardAposentadoria)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frMain = QtWidgets.QFrame(wdgCardAposentadoria)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frMain.sizePolicy().hasHeightForWidth())
        self.frMain.setSizePolicy(sizePolicy)
        self.frMain.setMinimumSize(QtCore.QSize(253, 264))
        self.frMain.setMaximumSize(QtCore.QSize(253, 264))
        self.frMain.setObjectName("frMain")
        self.gridLayout = QtWidgets.QGridLayout(self.frMain)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.pbarPrincipal = QtWidgets.QProgressBar(self.frMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbarPrincipal.sizePolicy().hasHeightForWidth())
        self.pbarPrincipal.setSizePolicy(sizePolicy)
        self.pbarPrincipal.setProperty("value", 24)
        self.pbarPrincipal.setFormat("")
        self.pbarPrincipal.setObjectName("pbarPrincipal")
        self.gridLayout.addWidget(self.pbarPrincipal, 6, 0, 1, 2)
        self.lbIdade = QtWidgets.QLabel(self.frMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbIdade.sizePolicy().hasHeightForWidth())
        self.lbIdade.setSizePolicy(sizePolicy)
        self.lbIdade.setAlignment(QtCore.Qt.AlignCenter)
        self.lbIdade.setObjectName("lbIdade")
        self.gridLayout.addWidget(self.lbIdade, 3, 0, 1, 2)
        self.lbQtdContrib = QtWidgets.QLabel(self.frMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbQtdContrib.sizePolicy().hasHeightForWidth())
        self.lbQtdContrib.setSizePolicy(sizePolicy)
        self.lbQtdContrib.setAlignment(QtCore.Qt.AlignCenter)
        self.lbQtdContrib.setObjectName("lbQtdContrib")
        self.gridLayout.addWidget(self.lbQtdContrib, 5, 0, 1, 2)
        self.lbTipoApos = QtWidgets.QLabel(self.frMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbTipoApos.sizePolicy().hasHeightForWidth())
        self.lbTipoApos.setSizePolicy(sizePolicy)
        self.lbTipoApos.setTextFormat(QtCore.Qt.AutoText)
        self.lbTipoApos.setScaledContents(False)
        self.lbTipoApos.setAlignment(QtCore.Qt.AlignCenter)
        self.lbTipoApos.setWordWrap(True)
        self.lbTipoApos.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lbTipoApos.setObjectName("lbTipoApos")
        self.gridLayout.addWidget(self.lbTipoApos, 2, 0, 1, 2)
        self.frBottom = QtWidgets.QFrame(self.frMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frBottom.sizePolicy().hasHeightForWidth())
        self.frBottom.setSizePolicy(sizePolicy)
        self.frBottom.setMinimumSize(QtCore.QSize(249, 60))
        self.frBottom.setMaximumSize(QtCore.QSize(249, 60))
        self.frBottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frBottom.setObjectName("frBottom")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frBottom)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbValorBeneficio = QtWidgets.QLabel(self.frBottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbValorBeneficio.sizePolicy().hasHeightForWidth())
        self.lbValorBeneficio.setSizePolicy(sizePolicy)
        self.lbValorBeneficio.setMinimumSize(QtCore.QSize(0, 60))
        self.lbValorBeneficio.setAlignment(QtCore.Qt.AlignCenter)
        self.lbValorBeneficio.setObjectName("lbValorBeneficio")
        self.horizontalLayout_2.addWidget(self.lbValorBeneficio)
        self.gridLayout.addWidget(self.frBottom, 9, 0, 1, 2)
        self.lbDib = QtWidgets.QLabel(self.frMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbDib.sizePolicy().hasHeightForWidth())
        self.lbDib.setSizePolicy(sizePolicy)
        self.lbDib.setAlignment(QtCore.Qt.AlignCenter)
        self.lbDib.setObjectName("lbDib")
        self.gridLayout.addWidget(self.lbDib, 7, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 2)
        self.horizontalLayout.addWidget(self.frMain)

        self.retranslateUi(wdgCardAposentadoria)
        QtCore.QMetaObject.connectSlotsByName(wdgCardAposentadoria)

    def retranslateUi(self, wdgCardAposentadoria):
        _translate = QtCore.QCoreApplication.translate
        wdgCardAposentadoria.setWindowTitle(_translate("wdgCardAposentadoria", "Form"))
        self.lbIdade.setText(_translate("wdgCardAposentadoria", "65 anos"))
        self.lbQtdContrib.setText(_translate("wdgCardAposentadoria", "Qtd de contribuições - 15/180"))
        self.lbTipoApos.setText(_translate("wdgCardAposentadoria", "Tipo de aposentadoria"))
        self.lbValorBeneficio.setText(_translate("wdgCardAposentadoria", "R$ 1900,00"))
        self.lbDib.setText(_translate("wdgCardAposentadoria", "DIB: 15/10/2023"))
import Resources.wdgCardAposentadoria


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgCardAposentadoria = QtWidgets.QWidget()
    ui = Ui_wdgCardAposentadoria()
    ui.setupUi(wdgCardAposentadoria)
    wdgCardAposentadoria.show()
    sys.exit(app.exec_())
