# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design/UI/wdgCardAposentadoria.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgCardAposentadoria(object):
    def setupUi(self, wdgCardAposentadoria):
        wdgCardAposentadoria.setObjectName("wdgCardAposentadoria")
        wdgCardAposentadoria.resize(374, 432)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wdgCardAposentadoria.sizePolicy().hasHeightForWidth())
        wdgCardAposentadoria.setSizePolicy(sizePolicy)
        wdgCardAposentadoria.setMaximumSize(QtCore.QSize(380, 450))
        wdgCardAposentadoria.setStyleSheet("/*#wdgCardAposentadoria {\n"
"    background-color: black;\n"
"}*/\n"
"\n"
"/*------------------------------------- Label -------------------------------------*/\n"
"#lbDib, #lbInfoDib {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 10px;\n"
"\n"
"    color: grey;\n"
"}\n"
"\n"
"#lbQtdContrib, #lbValorBeneficio {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 18px;\n"
"    font-weight: 600;\n"
"\n"
"    color: rgb(44, 44, 44);\n"
"}\n"
"\n"
"#lbInfoQtdContrib, #lbInfoValorBeneficio,\n"
"#lbInfoTipoSimulacao, #lbTipoSimulacao {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 12px;\n"
"\n"
"    color: rgb(44, 44, 44);\n"
"}\n"
"\n"
"#lbIdade {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 22px;\n"
"\n"
"    color: white;\n"
"}\n"
"\n"
"#lbTipoApos {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 22px;\n"
"\n"
"    color: grey;\n"
"}\n"
"\n"
"/*------------------------------------- Frame -------------------------------------*/\n"
"#frIconeCentral {\n"
"    border-width: 0px;\n"
"    border-color: grey;\n"
"    border-style: solid;\n"
"\n"
"    border-radius: 60px;\n"
"    background-color: rgb(250, 156, 62);\n"
"}\n"
"\n"
"#frSeparador1 {\n"
"    background-color: lightgrey;\n"
"}\n"
"\n"
"/*------------------------------------- Group Box -------------------------------------*/\n"
"#gbMain {\n"
"    background-color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"#gbMain::title {\n"
"    margin-top: 4px;\n"
"    margin-left: 4px;\n"
"}\n"
"\n"
"#gbMain::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"#gbMain::indicator:checked {\n"
"    background-image: url(:/checkCard/entrevista-check.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;    \n"
"}\n"
"\n"
"/*------------------------------------- Progress Bar  -------------------------------------*/\n"
"#pbarPrincipal {\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#pbarPrincipal::chunk {\n"
"    background-color: #05B8CC;\n"
"    width: 20px;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(wdgCardAposentadoria)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gbMain = QtWidgets.QGroupBox(wdgCardAposentadoria)
        self.gbMain.setCheckable(True)
        self.gbMain.setObjectName("gbMain")
        self.gridLayout = QtWidgets.QGridLayout(self.gbMain)
        self.gridLayout.setObjectName("gridLayout")
        self.lbInfoDib = QtWidgets.QLabel(self.gbMain)
        self.lbInfoDib.setObjectName("lbInfoDib")
        self.gridLayout.addWidget(self.lbInfoDib, 0, 1, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.gbMain)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frIconeCentral = QtWidgets.QFrame(self.frame)
        self.frIconeCentral.setMinimumSize(QtCore.QSize(120, 120))
        self.frIconeCentral.setMaximumSize(QtCore.QSize(120, 120))
        self.frIconeCentral.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frIconeCentral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frIconeCentral.setObjectName("frIconeCentral")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frIconeCentral)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbIdade = QtWidgets.QLabel(self.frIconeCentral)
        self.lbIdade.setObjectName("lbIdade")
        self.horizontalLayout_3.addWidget(self.lbIdade, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_4.addWidget(self.frIconeCentral)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 3)
        self.lbDib = QtWidgets.QLabel(self.gbMain)
        self.lbDib.setObjectName("lbDib")
        self.gridLayout.addWidget(self.lbDib, 0, 2, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.frame_3 = QtWidgets.QFrame(self.gbMain)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 16, 0, 0)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbValorBeneficio = QtWidgets.QLabel(self.frame_3)
        self.lbValorBeneficio.setObjectName("lbValorBeneficio")
        self.verticalLayout_2.addWidget(self.lbValorBeneficio, 0, QtCore.Qt.AlignHCenter)
        self.lbInfoValorBeneficio = QtWidgets.QLabel(self.frame_3)
        self.lbInfoValorBeneficio.setObjectName("lbInfoValorBeneficio")
        self.verticalLayout_2.addWidget(self.lbInfoValorBeneficio, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addWidget(self.frame_3, 5, 1, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.gbMain)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 16, 0, 0)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbQtdContrib = QtWidgets.QLabel(self.frame_2)
        self.lbQtdContrib.setObjectName("lbQtdContrib")
        self.verticalLayout.addWidget(self.lbQtdContrib, 0, QtCore.Qt.AlignHCenter)
        self.lbInfoQtdContrib = QtWidgets.QLabel(self.frame_2)
        self.lbInfoQtdContrib.setObjectName("lbInfoQtdContrib")
        self.verticalLayout.addWidget(self.lbInfoQtdContrib, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout.addWidget(self.frame_2, 5, 0, 1, 1)
        self.lbTipoApos = QtWidgets.QLabel(self.gbMain)
        self.lbTipoApos.setAlignment(QtCore.Qt.AlignCenter)
        self.lbTipoApos.setWordWrap(True)
        self.lbTipoApos.setObjectName("lbTipoApos")
        self.gridLayout.addWidget(self.lbTipoApos, 3, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.pbarPrincipal = QtWidgets.QProgressBar(self.gbMain)
        self.pbarPrincipal.setProperty("value", 24)
        self.pbarPrincipal.setFormat("")
        self.pbarPrincipal.setObjectName("pbarPrincipal")
        self.gridLayout.addWidget(self.pbarPrincipal, 4, 0, 1, 3)
        self.frame_4 = QtWidgets.QFrame(self.gbMain)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbInfoTipoSimulacao = QtWidgets.QLabel(self.frame_4)
        self.lbInfoTipoSimulacao.setObjectName("lbInfoTipoSimulacao")
        self.horizontalLayout_2.addWidget(self.lbInfoTipoSimulacao, 0, QtCore.Qt.AlignRight)
        self.lbTipoSimulacao = QtWidgets.QLabel(self.frame_4)
        self.lbTipoSimulacao.setObjectName("lbTipoSimulacao")
        self.horizontalLayout_2.addWidget(self.lbTipoSimulacao, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addWidget(self.frame_4, 7, 0, 1, 3)
        self.frSeparador1 = QtWidgets.QFrame(self.gbMain)
        self.frSeparador1.setMinimumSize(QtCore.QSize(0, 2))
        self.frSeparador1.setMaximumSize(QtCore.QSize(16777215, 2))
        self.frSeparador1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frSeparador1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frSeparador1.setObjectName("frSeparador1")
        self.gridLayout.addWidget(self.frSeparador1, 6, 0, 1, 3)
        self.horizontalLayout.addWidget(self.gbMain)

        self.retranslateUi(wdgCardAposentadoria)
        QtCore.QMetaObject.connectSlotsByName(wdgCardAposentadoria)

    def retranslateUi(self, wdgCardAposentadoria):
        _translate = QtCore.QCoreApplication.translate
        wdgCardAposentadoria.setWindowTitle(_translate("wdgCardAposentadoria", "Form"))
        self.lbInfoDib.setText(_translate("wdgCardAposentadoria", "DIB:"))
        self.lbIdade.setText(_translate("wdgCardAposentadoria", "56 anos"))
        self.lbDib.setText(_translate("wdgCardAposentadoria", "15/10/2023"))
        self.lbValorBeneficio.setText(_translate("wdgCardAposentadoria", "valorBeneficio"))
        self.lbInfoValorBeneficio.setText(_translate("wdgCardAposentadoria", "Valor do benefício"))
        self.lbQtdContrib.setText(_translate("wdgCardAposentadoria", "QtdContribuicoes"))
        self.lbInfoQtdContrib.setText(_translate("wdgCardAposentadoria", "Quantidade de contribuições"))
        self.lbTipoApos.setText(_translate("wdgCardAposentadoria", "Tipo de aposentadoria"))
        self.lbInfoTipoSimulacao.setText(_translate("wdgCardAposentadoria", "Simulação:"))
        self.lbTipoSimulacao.setText(_translate("wdgCardAposentadoria", "Repetição da última contribuição"))
import Resources.wdgCardAposentadoria


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgCardAposentadoria = QtWidgets.QWidget()
    ui = Ui_wdgCardAposentadoria()
    ui.setupUi(wdgCardAposentadoria)
    wdgCardAposentadoria.show()
    sys.exit(app.exec_())
