# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design/UI/wdgEnviaCNIS.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgEnviaCNIS(object):
    def setupUi(self, wdgEnviaCNIS):
        wdgEnviaCNIS.setObjectName("wdgEnviaCNIS")
        wdgEnviaCNIS.resize(587, 325)
        wdgEnviaCNIS.setStyleSheet("#wdgEnviaCNIS {\n"
"    background-color: lightgrey;\n"
"}\n"
"\n"
"/*---------------------------------------- Frame ----------------------------------------*/\n"
"#frPrincipal, #frTop, #frBottom{\n"
"    background-color: white;\n"
"    border-radius: 12px;\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"#frMiddle {\n"
"    border: 0px solid transparent;\n"
"    background-color: lightgrey;\n"
"}\n"
"\n"
"#frIcone {\n"
"    background-image: url(:/upload/enviaArquivo.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"/*---------------------------------------- Label ----------------------------------------*/\n"
"#lbTitulo {\n"
"    font: 24pt \"Bebas Neue\";\n"
"    color: #009E38;\n"
"}\n"
"\n"
"#lbSubtitulo, #lbInfoBottom {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: #52555A;\n"
"}\n"
"\n"
"/*---------------------------------- Push button ---------------------------------*/\n"
"#pbBuscaCNIS {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: #52555A;\n"
"\n"
"    background-color: white;\n"
"    border: 0px solid white;\n"
"}\n"
"\n"
"#pbCadSemCnis {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: white;\n"
"\n"
"    background-color: #009E38;\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 12px;\n"
"    border-bottom-left-radius: 12px;\n"
"}\n"
"\n"
"#pbCadSemCnis:hover {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: white;\n"
"\n"
"    background-color: #23E386;\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 12px;\n"
"    border-bottom-left-radius: 12px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(wdgEnviaCNIS)
        self.gridLayout.setObjectName("gridLayout")
        self.frPrincipal = QtWidgets.QFrame(wdgEnviaCNIS)
        self.frPrincipal.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.frPrincipal.setAcceptDrops(True)
        self.frPrincipal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frPrincipal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frPrincipal.setObjectName("frPrincipal")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frPrincipal)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frTop = QtWidgets.QFrame(self.frPrincipal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frTop.sizePolicy().hasHeightForWidth())
        self.frTop.setSizePolicy(sizePolicy)
        self.frTop.setMinimumSize(QtCore.QSize(0, 0))
        self.frTop.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frTop.setObjectName("frTop")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frTop)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.lbTitulo = QtWidgets.QLabel(self.frTop)
        self.lbTitulo.setObjectName("lbTitulo")
        self.verticalLayout_2.addWidget(self.lbTitulo, 0, QtCore.Qt.AlignHCenter)
        self.lbSubtitulo = QtWidgets.QLabel(self.frTop)
        self.lbSubtitulo.setObjectName("lbSubtitulo")
        self.verticalLayout_2.addWidget(self.lbSubtitulo, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frTop)
        self.frMiddle = QtWidgets.QFrame(self.frPrincipal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frMiddle.sizePolicy().hasHeightForWidth())
        self.frMiddle.setSizePolicy(sizePolicy)
        self.frMiddle.setMinimumSize(QtCore.QSize(0, 2))
        self.frMiddle.setMaximumSize(QtCore.QSize(16777215, 2))
        self.frMiddle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frMiddle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frMiddle.setObjectName("frMiddle")
        self.verticalLayout.addWidget(self.frMiddle)
        self.frBottom = QtWidgets.QFrame(self.frPrincipal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frBottom.sizePolicy().hasHeightForWidth())
        self.frBottom.setSizePolicy(sizePolicy)
        self.frBottom.setMinimumSize(QtCore.QSize(0, 100))
        self.frBottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frBottom.setObjectName("frBottom")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frBottom)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.frIcone = QtWidgets.QFrame(self.frBottom)
        self.frIcone.setMinimumSize(QtCore.QSize(30, 30))
        self.frIcone.setMaximumSize(QtCore.QSize(30, 30))
        self.frIcone.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frIcone.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frIcone.setObjectName("frIcone")
        self.horizontalLayout.addWidget(self.frIcone)
        self.pbBuscaCNIS = QtWidgets.QPushButton(self.frBottom)
        self.pbBuscaCNIS.setObjectName("pbBuscaCNIS")
        self.horizontalLayout.addWidget(self.pbBuscaCNIS)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.frBottom)
        self.pbCadSemCnis = QtWidgets.QPushButton(self.frPrincipal)
        self.pbCadSemCnis.setMinimumSize(QtCore.QSize(0, 50))
        self.pbCadSemCnis.setObjectName("pbCadSemCnis")
        self.verticalLayout.addWidget(self.pbCadSemCnis)
        self.gridLayout.addWidget(self.frPrincipal, 0, 0, 1, 1)

        self.retranslateUi(wdgEnviaCNIS)
        QtCore.QMetaObject.connectSlotsByName(wdgEnviaCNIS)

    def retranslateUi(self, wdgEnviaCNIS):
        _translate = QtCore.QCoreApplication.translate
        wdgEnviaCNIS.setWindowTitle(_translate("wdgEnviaCNIS", "Form"))
        self.lbTitulo.setText(_translate("wdgEnviaCNIS", "PREENCHIMENTO AUTOMÁTICO"))
        self.lbSubtitulo.setText(_translate("wdgEnviaCNIS", "Cadastro a partir do CNIS"))
        self.pbBuscaCNIS.setText(_translate("wdgEnviaCNIS", "Arraste ou clique aqui para buscar o CNIS"))
        self.pbCadSemCnis.setText(_translate("wdgEnviaCNIS", "Cadastrar sem CNIS"))
import Resources.wdgEnviaCNIS


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgEnviaCNIS = QtWidgets.QWidget()
    ui = Ui_wdgEnviaCNIS()
    ui.setupUi(wdgEnviaCNIS)
    wdgEnviaCNIS.show()
    sys.exit(app.exec_())
