# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design/UI/wdgIndicador.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgIndicador(object):
    def setupUi(self, wdgIndicador):
        wdgIndicador.setObjectName("wdgIndicador")
        wdgIndicador.resize(256, 62)
        wdgIndicador.setStyleSheet("/* ---------------------------------------------- Frames ----------------------------------------------*/\n"
"#frMain {\n"
"    background-color: white;\n"
"    border-radius: 5px;\n"
"    \n"
"    border: 2px solid #F4F5F8;\n"
"}\n"
"\n"
"#frFirula {\n"
"    background-color: #3F64FF;\n"
"    \n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 0px; \n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 4px;\n"
"\n"
"    border-top: 2px solid #3F64FF;\n"
"    border-bottom: 2px solid #3F64FF;\n"
"    border-left: 2px solid #3F64FF;\n"
"    border-right: 0px solid none;\n"
"}\n"
"\n"
"/* ---------------------------------------------- CheckBox ----------------------------------------------*/\n"
"\n"
"#cbIndicador {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: #040D14;\n"
"}\n"
"\n"
"#cbIndicador::indicator:unchecked {\n"
"    image: url(:/indicador/CheckBoxFalse.png);\n"
"}\n"
"\n"
"#cbIndicador::indicator:checked {\n"
"    image: url(:/indicador/checkBoxTrue.png);\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(wdgIndicador)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frMain = QtWidgets.QFrame(wdgIndicador)
        self.frMain.setMinimumSize(QtCore.QSize(0, 40))
        self.frMain.setMaximumSize(QtCore.QSize(16777215, 42))
        self.frMain.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frMain.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frMain.setObjectName("frMain")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frMain)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 4, 0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frFirula = QtWidgets.QFrame(self.frMain)
        self.frFirula.setMaximumSize(QtCore.QSize(6, 16777215))
        self.frFirula.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frFirula.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frFirula.setObjectName("frFirula")
        self.horizontalLayout_2.addWidget(self.frFirula)
        self.cbIndicador = QtWidgets.QCheckBox(self.frMain)
        self.cbIndicador.setMinimumSize(QtCore.QSize(0, 40))
        self.cbIndicador.setMaximumSize(QtCore.QSize(16777215, 42))
        self.cbIndicador.setAutoFillBackground(False)
        self.cbIndicador.setIconSize(QtCore.QSize(20, 20))
        self.cbIndicador.setTristate(False)
        self.cbIndicador.setObjectName("cbIndicador")
        self.horizontalLayout_2.addWidget(self.cbIndicador, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.frMain)

        self.retranslateUi(wdgIndicador)
        QtCore.QMetaObject.connectSlotsByName(wdgIndicador)

    def retranslateUi(self, wdgIndicador):
        _translate = QtCore.QCoreApplication.translate
        wdgIndicador.setWindowTitle(_translate("wdgIndicador", "Form"))
        self.cbIndicador.setText(_translate("wdgIndicador", "CheckBox"))
import Resources.wdgIndicador


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgIndicador = QtWidgets.QWidget()
    ui = Ui_wdgIndicador()
    ui.setupUi(wdgIndicador)
    wdgIndicador.show()
    sys.exit(app.exec_())
