# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design/UI/wdgModalEntrevista.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mwModalEntrevista(object):
    def setupUi(self, mwModalEntrevista):
        mwModalEntrevista.setObjectName("mwModalEntrevista")
        mwModalEntrevista.resize(589, 684)
        mwModalEntrevista.setStyleSheet("/* ------------- Geral ------------------- */\n"
"QScrollArea, #scaPerguntas {\n"
"    background-color: white;\n"
"}\n"
"\n"
"/* ------------- Frames ----------------- */\n"
"#frInfoTitulo {\n"
"    background-color: white;\n"
"    border-radius: 5px;\n"
"    \n"
"    border: 2px solid #F4F5F8;\n"
"}\n"
"\n"
"#frFirula {\n"
"    background-color: #3F64FF;\n"
"    \n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 0px; \n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 4px;\n"
"\n"
"    border-top: 2px solid #3F64FF;\n"
"    border-bottom: 2px solid #3F64FF;\n"
"    border-left: 2px solid #3F64FF;\n"
"    border-right: 0px solid none;\n"
"}\n"
"\n"
"#frMain {\n"
"    background-color: white;\n"
"\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 8px; \n"
"    border-bottom-right-radius: 8px;\n"
"    border-bottom-left-radius: 0px\n"
"    \n"
"}\n"
"\n"
"#frShadow {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* ------------ Label -------------*/\n"
"\n"
"#lbInfo {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: #040D14;\n"
"\n"
"    font-weight: 150;\n"
"}\n"
"\n"
"#lbInfoPerguntas {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: #3F4E8C;\n"
"\n"
"    font-weight: 750;\n"
"}\n"
"\n"
"/*---------- Push Button -----------*/\n"
"#pbSalvar {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: white;\n"
"\n"
"    border-radius: 8px;\n"
"    background-color: #3F4E8C;\n"
"}\n"
"\n"
"#pbSalvar:hover {\n"
"    font: 12pt \"Avenir LT Std\";\n"
"    color: white;\n"
"\n"
"    border-radius: 8px;\n"
"    background-color: #566BBF;\n"
"}\n"
"\n"
"#pbFechar {\n"
"    background-image: url(:/botoes/closeLarge.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"\n"
"    border: 0px solid none;\n"
"    border-radius: 4px;\n"
"\n"
"    background-color: #F9F9F9;\n"
"}")
        self.wdgPrincipal = QtWidgets.QWidget(mwModalEntrevista)
        self.wdgPrincipal.setObjectName("wdgPrincipal")
        self.gridLayout = QtWidgets.QGridLayout(self.wdgPrincipal)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frShadow = QtWidgets.QFrame(self.wdgPrincipal)
        self.frShadow.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frShadow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frShadow.setObjectName("frShadow")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frShadow)
        self.gridLayout_3.setContentsMargins(0, 20, 20, 2)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frMain = QtWidgets.QFrame(self.frShadow)
        self.frMain.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frMain.setObjectName("frMain")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frMain)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pbFechar = QtWidgets.QPushButton(self.frMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbFechar.sizePolicy().hasHeightForWidth())
        self.pbFechar.setSizePolicy(sizePolicy)
        self.pbFechar.setMinimumSize(QtCore.QSize(35, 35))
        self.pbFechar.setMaximumSize(QtCore.QSize(35, 35))
        self.pbFechar.setText("")
        self.pbFechar.setObjectName("pbFechar")
        self.gridLayout_2.addWidget(self.pbFechar, 0, 1, 1, 1)
        self.frPerguntas = QtWidgets.QFrame(self.frMain)
        self.frPerguntas.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frPerguntas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frPerguntas.setObjectName("frPerguntas")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frPerguntas)
        self.verticalLayout.setContentsMargins(-1, 24, -1, -1)
        self.verticalLayout.setSpacing(18)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbInfoPerguntas = QtWidgets.QLabel(self.frPerguntas)
        self.lbInfoPerguntas.setObjectName("lbInfoPerguntas")
        self.verticalLayout.addWidget(self.lbInfoPerguntas)
        self.scrollArea = QtWidgets.QScrollArea(self.frPerguntas)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scaPerguntas = QtWidgets.QWidget()
        self.scaPerguntas.setGeometry(QtCore.QRect(0, 0, 492, 427))
        self.scaPerguntas.setObjectName("scaPerguntas")
        self.scrollArea.setWidget(self.scaPerguntas)
        self.verticalLayout.addWidget(self.scrollArea)
        self.gridLayout_2.addWidget(self.frPerguntas, 2, 0, 1, 1)
        self.pbSalvar = QtWidgets.QPushButton(self.frMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbSalvar.sizePolicy().hasHeightForWidth())
        self.pbSalvar.setSizePolicy(sizePolicy)
        self.pbSalvar.setMinimumSize(QtCore.QSize(180, 56))
        self.pbSalvar.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pbSalvar.setObjectName("pbSalvar")
        self.gridLayout_2.addWidget(self.pbSalvar, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.frInfoTitulo = QtWidgets.QFrame(self.frMain)
        self.frInfoTitulo.setMinimumSize(QtCore.QSize(0, 40))
        self.frInfoTitulo.setMaximumSize(QtCore.QSize(16777215, 42))
        self.frInfoTitulo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frInfoTitulo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frInfoTitulo.setObjectName("frInfoTitulo")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frInfoTitulo)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 4, 0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frFirula = QtWidgets.QFrame(self.frInfoTitulo)
        self.frFirula.setMaximumSize(QtCore.QSize(6, 16777215))
        self.frFirula.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frFirula.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frFirula.setObjectName("frFirula")
        self.horizontalLayout_2.addWidget(self.frFirula)
        self.lbInfo = QtWidgets.QLabel(self.frInfoTitulo)
        self.lbInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbInfo.setObjectName("lbInfo")
        self.horizontalLayout_2.addWidget(self.lbInfo)
        self.gridLayout_2.addWidget(self.frInfoTitulo, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frMain, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frShadow, 0, 0, 1, 1)
        mwModalEntrevista.setCentralWidget(self.wdgPrincipal)

        self.retranslateUi(mwModalEntrevista)
        QtCore.QMetaObject.connectSlotsByName(mwModalEntrevista)

    def retranslateUi(self, mwModalEntrevista):
        _translate = QtCore.QCoreApplication.translate
        mwModalEntrevista.setWindowTitle(_translate("mwModalEntrevista", "MainWindow"))
        self.lbInfoPerguntas.setText(_translate("mwModalEntrevista", "TextLabel"))
        self.pbSalvar.setText(_translate("mwModalEntrevista", "Salvar"))
        self.lbInfo.setText(_translate("mwModalEntrevista", "TextLabel"))
import Resources.wdgModalEntrevista


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mwModalEntrevista = QtWidgets.QMainWindow()
    ui = Ui_mwModalEntrevista()
    ui.setupUi(mwModalEntrevista)
    mwModalEntrevista.show()
    sys.exit(app.exec_())
