# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design/UI/wdgMenuPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgMenuPrincipal(object):
    def setupUi(self, wdgMenuPrincipal):
        wdgMenuPrincipal.setObjectName("wdgMenuPrincipal")
        wdgMenuPrincipal.resize(200, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wdgMenuPrincipal.sizePolicy().hasHeightForWidth())
        wdgMenuPrincipal.setSizePolicy(sizePolicy)
        wdgMenuPrincipal.setMinimumSize(QtCore.QSize(200, 200))
        wdgMenuPrincipal.setStyleSheet("/*#wdgMenuPrincipal {\n"
"    background-color: lightgrey;\n"
"}*/\n"
"\n"
"/*--------------------------------- Frame ---------------------------------*/\n"
"#frPrincipal {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    \n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(wdgMenuPrincipal)
        self.verticalLayout.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frPrincipal = QtWidgets.QFrame(wdgMenuPrincipal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frPrincipal.sizePolicy().hasHeightForWidth())
        self.frPrincipal.setSizePolicy(sizePolicy)
        self.frPrincipal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frPrincipal.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frPrincipal.setObjectName("frPrincipal")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frPrincipal)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.glPrincipal = QtWidgets.QGridLayout()
        self.glPrincipal.setSpacing(2)
        self.glPrincipal.setObjectName("glPrincipal")
        self.verticalLayout_2.addLayout(self.glPrincipal)
        self.verticalLayout.addWidget(self.frPrincipal)

        self.retranslateUi(wdgMenuPrincipal)
        QtCore.QMetaObject.connectSlotsByName(wdgMenuPrincipal)

    def retranslateUi(self, wdgMenuPrincipal):
        _translate = QtCore.QCoreApplication.translate
        wdgMenuPrincipal.setWindowTitle(_translate("wdgMenuPrincipal", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgMenuPrincipal = QtWidgets.QWidget()
    ui = Ui_wdgMenuPrincipal()
    ui.setupUi(wdgMenuPrincipal)
    wdgMenuPrincipal.show()
    sys.exit(app.exec_())
