# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design/UI/wdgTagFiltro.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgTagFiltro(object):
    def setupUi(self, wdgTagFiltro):
        wdgTagFiltro.setObjectName("wdgTagFiltro")
        wdgTagFiltro.resize(94, 52)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wdgTagFiltro.sizePolicy().hasHeightForWidth())
        wdgTagFiltro.setSizePolicy(sizePolicy)
        wdgTagFiltro.setStyleSheet("/*-------------------------------------- Frame --------------------------------------*/\n"
"#frMain {\n"
"    background-color: rgb(207, 242, 220);\n"
"    border-color: rgb(0, 158, 56);\n"
"    border-radius: 4px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"/*-------------------------------------- Label --------------------------------------*/\n"
"#lbFiltro {\n"
"    font-family: \"TeX Gyre Adventor\";\n"
"    font-size: 14px;\n"
"    color: rgb(59, 59, 59);\n"
"}\n"
"\n"
"/*-------------------------------------- Push Button --------------------------------------*/\n"
"#pbExcluir {\n"
"    background-color: transparent;\n"
"    background-image: url(:/fechar/entrevista-uncheck.png);\n"
"    background-repeat: no-repeat;    \n"
"    background-position: center;\n"
"}")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(wdgTagFiltro)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frMain = QtWidgets.QFrame(wdgTagFiltro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frMain.sizePolicy().hasHeightForWidth())
        self.frMain.setSizePolicy(sizePolicy)
        self.frMain.setMinimumSize(QtCore.QSize(0, 24))
        self.frMain.setMaximumSize(QtCore.QSize(16777215, 24))
        self.frMain.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frMain.setObjectName("frMain")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frMain)
        self.horizontalLayout.setContentsMargins(4, 0, 0, 0)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbFiltro = QtWidgets.QLabel(self.frMain)
        self.lbFiltro.setObjectName("lbFiltro")
        self.horizontalLayout.addWidget(self.lbFiltro)
        self.pbExcluir = QtWidgets.QPushButton(self.frMain)
        self.pbExcluir.setMinimumSize(QtCore.QSize(0, 22))
        self.pbExcluir.setMaximumSize(QtCore.QSize(16, 22))
        self.pbExcluir.setText("")
        self.pbExcluir.setObjectName("pbExcluir")
        self.horizontalLayout.addWidget(self.pbExcluir, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2.addWidget(self.frMain)

        self.retranslateUi(wdgTagFiltro)
        QtCore.QMetaObject.connectSlotsByName(wdgTagFiltro)

    def retranslateUi(self, wdgTagFiltro):
        _translate = QtCore.QCoreApplication.translate
        wdgTagFiltro.setWindowTitle(_translate("wdgTagFiltro", "Form"))
        self.lbFiltro.setText(_translate("wdgTagFiltro", "Filtro"))
import Resources.wdgTagFiltro


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wdgTagFiltro = QtWidgets.QWidget()
    ui = Ui_wdgTagFiltro()
    ui.setupUi(wdgTagFiltro)
    wdgTagFiltro.show()
    sys.exit(app.exec_())
